// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: enums_productinfo.proto
// Protobuf C++ Version: 6.33.5

#ifndef enums_5fproductinfo_2eproto_2epb_2eh
#define enums_5fproductinfo_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "steammessages_base.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_enums_5fproductinfo_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_enums_5fproductinfo_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_enums_5fproductinfo_2eproto;
}  // extern "C"
enum EContentDescriptorID : int;
extern const uint32_t EContentDescriptorID_internal_data_[];
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::EContentDescriptorID_internal_data_>
    internal::EnumTraitsImpl::value<::EContentDescriptorID>;
}  // namespace protobuf
}  // namespace google

enum EContentDescriptorID : int {
  k_EContentDescriptor_NudityOrSexualContent = 1,
  k_EContentDescriptor_FrequentViolenceOrGore = 2,
  k_EContentDescriptor_AdultOnlySexualContent = 3,
  k_EContentDescriptor_GratuitousSexualContent = 4,
  k_EContentDescriptor_AnyMatureContent = 5,
  k_EContentDescriptorMAX = 6,
};

extern const uint32_t EContentDescriptorID_internal_data_[];
inline constexpr EContentDescriptorID EContentDescriptorID_MIN =
    static_cast<EContentDescriptorID>(1);
inline constexpr EContentDescriptorID EContentDescriptorID_MAX =
    static_cast<EContentDescriptorID>(6);
inline bool EContentDescriptorID_IsValid(int value) {
  return 1 <= value && value <= 6;
}
inline constexpr int EContentDescriptorID_ARRAYSIZE = 6 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL EContentDescriptorID_descriptor();
template <typename T>
const ::std::string& EContentDescriptorID_Name(T value) {
  static_assert(::std::is_same<T, EContentDescriptorID>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EContentDescriptorID_Name().");
  return EContentDescriptorID_Name(static_cast<EContentDescriptorID>(value));
}
template <>
inline const ::std::string& EContentDescriptorID_Name(EContentDescriptorID value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EContentDescriptorID_descriptor, 1, 6>(
      static_cast<int>(value));
}
inline bool EContentDescriptorID_Parse(
    ::absl::string_view name, EContentDescriptorID* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<EContentDescriptorID>(EContentDescriptorID_descriptor(), name,
                                           value);
}

// ===================================================================



// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::EContentDescriptorID> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::EContentDescriptorID>() {
  return ::EContentDescriptorID_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // enums_5fproductinfo_2eproto_2epb_2eh
