// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: steammessages_unified_base.proto
// Protobuf C++ Version: 6.33.5

#ifndef steammessages_5funified_5fbase_2eproto_2epb_2eh
#define steammessages_5funified_5fbase_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_steammessages_5funified_5fbase_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_steammessages_5funified_5fbase_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_steammessages_5funified_5fbase_2eproto;
}  // extern "C"
enum EProtoExecutionSite : int;
extern const uint32_t EProtoExecutionSite_internal_data_[];
enum EProtoServiceType : int;
extern const uint32_t EProtoServiceType_internal_data_[];
class NoResponse;
struct NoResponseDefaultTypeInternal;
extern NoResponseDefaultTypeInternal _NoResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull NoResponse_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::EProtoExecutionSite_internal_data_>
    internal::EnumTraitsImpl::value<::EProtoExecutionSite>;
template <>
internal::EnumTraitsT<::EProtoServiceType_internal_data_>
    internal::EnumTraitsImpl::value<::EProtoServiceType>;
}  // namespace protobuf
}  // namespace google

enum EProtoExecutionSite : int {
  k_EProtoExecutionSiteUnknown = 0,
  k_EProtoExecutionSiteSteamClient = 2,
};

extern const uint32_t EProtoExecutionSite_internal_data_[];
inline constexpr EProtoExecutionSite EProtoExecutionSite_MIN =
    static_cast<EProtoExecutionSite>(0);
inline constexpr EProtoExecutionSite EProtoExecutionSite_MAX =
    static_cast<EProtoExecutionSite>(2);
inline bool EProtoExecutionSite_IsValid(int value) {
  return 0 <= value && value <= 2 && ((5u >> value) & 1) != 0;
}
inline constexpr int EProtoExecutionSite_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL EProtoExecutionSite_descriptor();
template <typename T>
const ::std::string& EProtoExecutionSite_Name(T value) {
  static_assert(::std::is_same<T, EProtoExecutionSite>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EProtoExecutionSite_Name().");
  return EProtoExecutionSite_Name(static_cast<EProtoExecutionSite>(value));
}
template <>
inline const ::std::string& EProtoExecutionSite_Name(EProtoExecutionSite value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EProtoExecutionSite_descriptor, 0, 2>(
      static_cast<int>(value));
}
inline bool EProtoExecutionSite_Parse(
    ::absl::string_view name, EProtoExecutionSite* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<EProtoExecutionSite>(EProtoExecutionSite_descriptor(), name,
                                           value);
}
enum EProtoServiceType : int {
  k_EProtoServiceTypeSteamMessages = 0,
  k_EProtoServiceTypeVRGamepadUIMessages = 1,
};

extern const uint32_t EProtoServiceType_internal_data_[];
inline constexpr EProtoServiceType EProtoServiceType_MIN =
    static_cast<EProtoServiceType>(0);
inline constexpr EProtoServiceType EProtoServiceType_MAX =
    static_cast<EProtoServiceType>(1);
inline bool EProtoServiceType_IsValid(int value) {
  return 0 <= value && value <= 1;
}
inline constexpr int EProtoServiceType_ARRAYSIZE = 1 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL EProtoServiceType_descriptor();
template <typename T>
const ::std::string& EProtoServiceType_Name(T value) {
  static_assert(::std::is_same<T, EProtoServiceType>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EProtoServiceType_Name().");
  return EProtoServiceType_Name(static_cast<EProtoServiceType>(value));
}
template <>
inline const ::std::string& EProtoServiceType_Name(EProtoServiceType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EProtoServiceType_descriptor, 0, 1>(
      static_cast<int>(value));
}
inline bool EProtoServiceType_Parse(
    ::absl::string_view name, EProtoServiceType* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<EProtoServiceType>(EProtoServiceType_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class NoResponse final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:NoResponse) */ {
 public:
  inline NoResponse() : NoResponse(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(NoResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(NoResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR NoResponse(::google::protobuf::internal::ConstantInitialized);

  inline NoResponse(const NoResponse& from) : NoResponse(nullptr, from) {}
  inline NoResponse(NoResponse&& from) noexcept
      : NoResponse(nullptr, ::std::move(from)) {}
  inline NoResponse& operator=(const NoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline NoResponse& operator=(NoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NoResponse& default_instance() {
    return *reinterpret_cast<const NoResponse*>(
        &_NoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(NoResponse& a, NoResponse& b) { a.Swap(&b); }
  inline void Swap(NoResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NoResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NoResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<NoResponse>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const NoResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const NoResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "NoResponse"; }

  explicit NoResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  NoResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const NoResponse& from);
  NoResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, NoResponse&& from) noexcept
      : NoResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:NoResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_steammessages_5funified_5fbase_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull NoResponse_class_data_;

// ===================================================================



inline constexpr int kMessageDescriptionFieldNumber = 51000;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::MessageOptions, ::google::protobuf::internal::StringTypeTraits, 12, false>
    message_description;
inline constexpr int kForceEmitMessageFieldNumber = 50026;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::MessageOptions, ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>
    force_emit_message;
inline constexpr int kDescriptionFieldNumber = 50000;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FieldOptions, ::google::protobuf::internal::StringTypeTraits, 12, false>
    description;
inline constexpr int kServiceDescriptionFieldNumber = 50000;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::ServiceOptions, ::google::protobuf::internal::StringTypeTraits, 12, false>
    service_description;
inline constexpr int kServiceExecutionSiteFieldNumber = 50008;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::ServiceOptions, ::google::protobuf::internal::EnumTypeTraits< ::EProtoExecutionSite>, 14, false>
    service_execution_site;
inline constexpr int kServiceTypeFieldNumber = 50025;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::ServiceOptions, ::google::protobuf::internal::EnumTypeTraits< ::EProtoServiceType>, 14, false>
    service_type;
inline constexpr int kForceEmitServiceFieldNumber = 50026;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::ServiceOptions, ::google::protobuf::internal::PrimitiveTypeTraits< bool >, 8, false>
    force_emit_service;
inline constexpr int kMethodDescriptionFieldNumber = 50000;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::MethodOptions, ::google::protobuf::internal::StringTypeTraits, 12, false>
    method_description;
inline constexpr int kEnumDescriptionFieldNumber = 50000;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::EnumOptions, ::google::protobuf::internal::StringTypeTraits, 12, false>
    enum_description;
inline constexpr int kEnumValueDescriptionFieldNumber = 50000;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::EnumValueOptions, ::google::protobuf::internal::StringTypeTraits, 12, false>
    enum_value_description;

// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// NoResponse

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::EProtoExecutionSite> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::EProtoExecutionSite>() {
  return ::EProtoExecutionSite_descriptor();
}
template <>
struct is_proto_enum<::EProtoServiceType> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::EProtoServiceType>() {
  return ::EProtoServiceType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // steammessages_5funified_5fbase_2eproto_2epb_2eh
