// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: steammessages_childprocessquery.proto
// Protobuf C++ Version: 6.33.5

#ifndef steammessages_5fchildprocessquery_2eproto_2epb_2eh
#define steammessages_5fchildprocessquery_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "enums.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_steammessages_5fchildprocessquery_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_steammessages_5fchildprocessquery_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_steammessages_5fchildprocessquery_2eproto;
}  // extern "C"
class CMsgChildProcessQueryGpuTopology;
struct CMsgChildProcessQueryGpuTopologyDefaultTypeInternal;
extern CMsgChildProcessQueryGpuTopologyDefaultTypeInternal _CMsgChildProcessQueryGpuTopology_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CMsgChildProcessQueryGpuTopology_class_data_;
class CMsgChildProcessQueryGpuTopology_GpuInfo;
struct CMsgChildProcessQueryGpuTopology_GpuInfoDefaultTypeInternal;
extern CMsgChildProcessQueryGpuTopology_GpuInfoDefaultTypeInternal _CMsgChildProcessQueryGpuTopology_GpuInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CMsgChildProcessQueryGpuTopology_GpuInfo_class_data_;
class CMsgChildProcessQueryResponse;
struct CMsgChildProcessQueryResponseDefaultTypeInternal;
extern CMsgChildProcessQueryResponseDefaultTypeInternal _CMsgChildProcessQueryResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CMsgChildProcessQueryResponse_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class CMsgChildProcessQueryGpuTopology_GpuInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CMsgChildProcessQueryGpuTopology.GpuInfo) */ {
 public:
  inline CMsgChildProcessQueryGpuTopology_GpuInfo() : CMsgChildProcessQueryGpuTopology_GpuInfo(nullptr) {}
  ~CMsgChildProcessQueryGpuTopology_GpuInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgChildProcessQueryGpuTopology_GpuInfo* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgChildProcessQueryGpuTopology_GpuInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CMsgChildProcessQueryGpuTopology_GpuInfo(::google::protobuf::internal::ConstantInitialized);

  inline CMsgChildProcessQueryGpuTopology_GpuInfo(const CMsgChildProcessQueryGpuTopology_GpuInfo& from) : CMsgChildProcessQueryGpuTopology_GpuInfo(nullptr, from) {}
  inline CMsgChildProcessQueryGpuTopology_GpuInfo(CMsgChildProcessQueryGpuTopology_GpuInfo&& from) noexcept
      : CMsgChildProcessQueryGpuTopology_GpuInfo(nullptr, ::std::move(from)) {}
  inline CMsgChildProcessQueryGpuTopology_GpuInfo& operator=(const CMsgChildProcessQueryGpuTopology_GpuInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgChildProcessQueryGpuTopology_GpuInfo& operator=(CMsgChildProcessQueryGpuTopology_GpuInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgChildProcessQueryGpuTopology_GpuInfo& default_instance() {
    return *reinterpret_cast<const CMsgChildProcessQueryGpuTopology_GpuInfo*>(
        &_CMsgChildProcessQueryGpuTopology_GpuInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CMsgChildProcessQueryGpuTopology_GpuInfo& a, CMsgChildProcessQueryGpuTopology_GpuInfo& b) { a.Swap(&b); }
  inline void Swap(CMsgChildProcessQueryGpuTopology_GpuInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgChildProcessQueryGpuTopology_GpuInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgChildProcessQueryGpuTopology_GpuInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CMsgChildProcessQueryGpuTopology_GpuInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CMsgChildProcessQueryGpuTopology_GpuInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CMsgChildProcessQueryGpuTopology_GpuInfo& from) { CMsgChildProcessQueryGpuTopology_GpuInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgChildProcessQueryGpuTopology_GpuInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgChildProcessQueryGpuTopology.GpuInfo"; }

  explicit CMsgChildProcessQueryGpuTopology_GpuInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgChildProcessQueryGpuTopology_GpuInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgChildProcessQueryGpuTopology_GpuInfo& from);
  CMsgChildProcessQueryGpuTopology_GpuInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgChildProcessQueryGpuTopology_GpuInfo&& from) noexcept
      : CMsgChildProcessQueryGpuTopology_GpuInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 2,
    kIdFieldNumber = 1,
    kDriverIdFieldNumber = 4,
    kVramSizeBytesFieldNumber = 3,
    kDriverVersionMajorFieldNumber = 5,
    kDriverVersionMinorFieldNumber = 6,
    kDriverVersionPatchFieldNumber = 7,
  };
  // optional string name = 2;
  bool has_name() const;
  void clear_name() ;
  const ::std::string& name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_name();
  void set_allocated_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_name();

  public:
  // optional uint32 id = 1;
  bool has_id() const;
  void clear_id() ;
  ::uint32_t id() const;
  void set_id(::uint32_t value);

  private:
  ::uint32_t _internal_id() const;
  void _internal_set_id(::uint32_t value);

  public:
  // optional .EGpuDriverId driver_id = 4 [default = k_EGpuDriverId_Invalid];
  bool has_driver_id() const;
  void clear_driver_id() ;
  ::EGpuDriverId driver_id() const;
  void set_driver_id(::EGpuDriverId value);

  private:
  ::EGpuDriverId _internal_driver_id() const;
  void _internal_set_driver_id(::EGpuDriverId value);

  public:
  // optional uint64 vram_size_bytes = 3;
  bool has_vram_size_bytes() const;
  void clear_vram_size_bytes() ;
  ::uint64_t vram_size_bytes() const;
  void set_vram_size_bytes(::uint64_t value);

  private:
  ::uint64_t _internal_vram_size_bytes() const;
  void _internal_set_vram_size_bytes(::uint64_t value);

  public:
  // optional int32 driver_version_major = 5;
  bool has_driver_version_major() const;
  void clear_driver_version_major() ;
  ::int32_t driver_version_major() const;
  void set_driver_version_major(::int32_t value);

  private:
  ::int32_t _internal_driver_version_major() const;
  void _internal_set_driver_version_major(::int32_t value);

  public:
  // optional int32 driver_version_minor = 6;
  bool has_driver_version_minor() const;
  void clear_driver_version_minor() ;
  ::int32_t driver_version_minor() const;
  void set_driver_version_minor(::int32_t value);

  private:
  ::int32_t _internal_driver_version_minor() const;
  void _internal_set_driver_version_minor(::int32_t value);

  public:
  // optional int32 driver_version_patch = 7;
  bool has_driver_version_patch() const;
  void clear_driver_version_patch() ;
  ::int32_t driver_version_patch() const;
  void set_driver_version_patch(::int32_t value);

  private:
  ::int32_t _internal_driver_version_patch() const;
  void _internal_set_driver_version_patch(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgChildProcessQueryGpuTopology.GpuInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 7,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgChildProcessQueryGpuTopology_GpuInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::uint32_t id_;
    int driver_id_;
    ::uint64_t vram_size_bytes_;
    ::int32_t driver_version_major_;
    ::int32_t driver_version_minor_;
    ::int32_t driver_version_patch_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5fchildprocessquery_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CMsgChildProcessQueryGpuTopology_GpuInfo_class_data_;
// -------------------------------------------------------------------

class CMsgChildProcessQueryGpuTopology final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CMsgChildProcessQueryGpuTopology) */ {
 public:
  inline CMsgChildProcessQueryGpuTopology() : CMsgChildProcessQueryGpuTopology(nullptr) {}
  ~CMsgChildProcessQueryGpuTopology() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgChildProcessQueryGpuTopology* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgChildProcessQueryGpuTopology));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CMsgChildProcessQueryGpuTopology(::google::protobuf::internal::ConstantInitialized);

  inline CMsgChildProcessQueryGpuTopology(const CMsgChildProcessQueryGpuTopology& from) : CMsgChildProcessQueryGpuTopology(nullptr, from) {}
  inline CMsgChildProcessQueryGpuTopology(CMsgChildProcessQueryGpuTopology&& from) noexcept
      : CMsgChildProcessQueryGpuTopology(nullptr, ::std::move(from)) {}
  inline CMsgChildProcessQueryGpuTopology& operator=(const CMsgChildProcessQueryGpuTopology& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgChildProcessQueryGpuTopology& operator=(CMsgChildProcessQueryGpuTopology&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgChildProcessQueryGpuTopology& default_instance() {
    return *reinterpret_cast<const CMsgChildProcessQueryGpuTopology*>(
        &_CMsgChildProcessQueryGpuTopology_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CMsgChildProcessQueryGpuTopology& a, CMsgChildProcessQueryGpuTopology& b) { a.Swap(&b); }
  inline void Swap(CMsgChildProcessQueryGpuTopology* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgChildProcessQueryGpuTopology* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgChildProcessQueryGpuTopology* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CMsgChildProcessQueryGpuTopology>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CMsgChildProcessQueryGpuTopology& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CMsgChildProcessQueryGpuTopology& from) { CMsgChildProcessQueryGpuTopology::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgChildProcessQueryGpuTopology* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgChildProcessQueryGpuTopology"; }

  explicit CMsgChildProcessQueryGpuTopology(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgChildProcessQueryGpuTopology(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgChildProcessQueryGpuTopology& from);
  CMsgChildProcessQueryGpuTopology(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgChildProcessQueryGpuTopology&& from) noexcept
      : CMsgChildProcessQueryGpuTopology(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using GpuInfo = CMsgChildProcessQueryGpuTopology_GpuInfo;

  // accessors -------------------------------------------------------
  enum : int {
    kGpusFieldNumber = 1,
    kDefaultGpuIdFieldNumber = 2,
  };
  // repeated .CMsgChildProcessQueryGpuTopology.GpuInfo gpus = 1;
  int gpus_size() const;
  private:
  int _internal_gpus_size() const;

  public:
  void clear_gpus() ;
  ::CMsgChildProcessQueryGpuTopology_GpuInfo* PROTOBUF_NONNULL mutable_gpus(int index);
  ::google::protobuf::RepeatedPtrField<::CMsgChildProcessQueryGpuTopology_GpuInfo>* PROTOBUF_NONNULL mutable_gpus();

  private:
  const ::google::protobuf::RepeatedPtrField<::CMsgChildProcessQueryGpuTopology_GpuInfo>& _internal_gpus() const;
  ::google::protobuf::RepeatedPtrField<::CMsgChildProcessQueryGpuTopology_GpuInfo>* PROTOBUF_NONNULL _internal_mutable_gpus();
  public:
  const ::CMsgChildProcessQueryGpuTopology_GpuInfo& gpus(int index) const;
  ::CMsgChildProcessQueryGpuTopology_GpuInfo* PROTOBUF_NONNULL add_gpus();
  const ::google::protobuf::RepeatedPtrField<::CMsgChildProcessQueryGpuTopology_GpuInfo>& gpus() const;
  // optional uint32 default_gpu_id = 2;
  bool has_default_gpu_id() const;
  void clear_default_gpu_id() ;
  ::uint32_t default_gpu_id() const;
  void set_default_gpu_id(::uint32_t value);

  private:
  ::uint32_t _internal_default_gpu_id() const;
  void _internal_set_default_gpu_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgChildProcessQueryGpuTopology)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgChildProcessQueryGpuTopology& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::CMsgChildProcessQueryGpuTopology_GpuInfo > gpus_;
    ::uint32_t default_gpu_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5fchildprocessquery_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CMsgChildProcessQueryGpuTopology_class_data_;
// -------------------------------------------------------------------

class CMsgChildProcessQueryResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CMsgChildProcessQueryResponse) */ {
 public:
  inline CMsgChildProcessQueryResponse() : CMsgChildProcessQueryResponse(nullptr) {}
  ~CMsgChildProcessQueryResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgChildProcessQueryResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgChildProcessQueryResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CMsgChildProcessQueryResponse(::google::protobuf::internal::ConstantInitialized);

  inline CMsgChildProcessQueryResponse(const CMsgChildProcessQueryResponse& from) : CMsgChildProcessQueryResponse(nullptr, from) {}
  inline CMsgChildProcessQueryResponse(CMsgChildProcessQueryResponse&& from) noexcept
      : CMsgChildProcessQueryResponse(nullptr, ::std::move(from)) {}
  inline CMsgChildProcessQueryResponse& operator=(const CMsgChildProcessQueryResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgChildProcessQueryResponse& operator=(CMsgChildProcessQueryResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgChildProcessQueryResponse& default_instance() {
    return *reinterpret_cast<const CMsgChildProcessQueryResponse*>(
        &_CMsgChildProcessQueryResponse_default_instance_);
  }
  enum ResponseCase {
    kGpuTopology = 1,
    RESPONSE_NOT_SET = 0,
  };
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CMsgChildProcessQueryResponse& a, CMsgChildProcessQueryResponse& b) { a.Swap(&b); }
  inline void Swap(CMsgChildProcessQueryResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgChildProcessQueryResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgChildProcessQueryResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CMsgChildProcessQueryResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CMsgChildProcessQueryResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CMsgChildProcessQueryResponse& from) { CMsgChildProcessQueryResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgChildProcessQueryResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgChildProcessQueryResponse"; }

  explicit CMsgChildProcessQueryResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgChildProcessQueryResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgChildProcessQueryResponse& from);
  CMsgChildProcessQueryResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgChildProcessQueryResponse&& from) noexcept
      : CMsgChildProcessQueryResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kGpuTopologyFieldNumber = 1,
  };
  // .CMsgChildProcessQueryGpuTopology gpu_topology = 1;
  bool has_gpu_topology() const;
  private:
  bool _internal_has_gpu_topology() const;

  public:
  void clear_gpu_topology() ;
  const ::CMsgChildProcessQueryGpuTopology& gpu_topology() const;
  [[nodiscard]] ::CMsgChildProcessQueryGpuTopology* PROTOBUF_NULLABLE release_gpu_topology();
  ::CMsgChildProcessQueryGpuTopology* PROTOBUF_NONNULL mutable_gpu_topology();
  void set_allocated_gpu_topology(::CMsgChildProcessQueryGpuTopology* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_gpu_topology(::CMsgChildProcessQueryGpuTopology* PROTOBUF_NULLABLE value);
  ::CMsgChildProcessQueryGpuTopology* PROTOBUF_NULLABLE unsafe_arena_release_gpu_topology();

  private:
  const ::CMsgChildProcessQueryGpuTopology& _internal_gpu_topology() const;
  ::CMsgChildProcessQueryGpuTopology* PROTOBUF_NONNULL _internal_mutable_gpu_topology();

  public:
  void clear_response();
  ResponseCase response_case() const;
  // @@protoc_insertion_point(class_scope:CMsgChildProcessQueryResponse)
 private:
  class _Internal;
  void set_has_gpu_topology();
  inline bool has_response() const;
  inline void clear_has_response();
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgChildProcessQueryResponse& from_msg);
    union ResponseUnion {
      constexpr ResponseUnion() : _constinit_{} {}
      ::google::protobuf::internal::ConstantInitialized _constinit_;
      ::CMsgChildProcessQueryGpuTopology* PROTOBUF_NULLABLE gpu_topology_;
    } response_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t _oneof_case_[1];
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5fchildprocessquery_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CMsgChildProcessQueryResponse_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CMsgChildProcessQueryResponse

// .CMsgChildProcessQueryGpuTopology gpu_topology = 1;
inline bool CMsgChildProcessQueryResponse::has_gpu_topology() const {
  return response_case() == kGpuTopology;
}
inline bool CMsgChildProcessQueryResponse::_internal_has_gpu_topology() const {
  return response_case() == kGpuTopology;
}
inline void CMsgChildProcessQueryResponse::set_has_gpu_topology() {
  _impl_._oneof_case_[0] = kGpuTopology;
}
inline void CMsgChildProcessQueryResponse::clear_gpu_topology() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (response_case() == kGpuTopology) {
    if (GetArena() == nullptr) {
      delete _impl_.response_.gpu_topology_;
    } else if (::google::protobuf::internal::DebugHardenClearOneofMessageOnArena()) {
      ::google::protobuf::internal::MaybePoisonAfterClear(_impl_.response_.gpu_topology_);
    }
    clear_has_response();
  }
}
inline ::CMsgChildProcessQueryGpuTopology* PROTOBUF_NULLABLE CMsgChildProcessQueryResponse::release_gpu_topology() {
  // @@protoc_insertion_point(field_release:CMsgChildProcessQueryResponse.gpu_topology)
  if (response_case() == kGpuTopology) {
    clear_has_response();
    auto* temp = _impl_.response_.gpu_topology_;
    if (GetArena() != nullptr) {
      temp = ::google::protobuf::internal::DuplicateIfNonNull(temp);
    }
    _impl_.response_.gpu_topology_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::CMsgChildProcessQueryGpuTopology& CMsgChildProcessQueryResponse::_internal_gpu_topology() const {
  return response_case() == kGpuTopology ? static_cast<const ::CMsgChildProcessQueryGpuTopology&>(*_impl_.response_.gpu_topology_)
                     : reinterpret_cast<const ::CMsgChildProcessQueryGpuTopology&>(::_CMsgChildProcessQueryGpuTopology_default_instance_);
}
inline const ::CMsgChildProcessQueryGpuTopology& CMsgChildProcessQueryResponse::gpu_topology() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CMsgChildProcessQueryResponse.gpu_topology)
  return _internal_gpu_topology();
}
inline ::CMsgChildProcessQueryGpuTopology* PROTOBUF_NULLABLE CMsgChildProcessQueryResponse::unsafe_arena_release_gpu_topology() {
  // @@protoc_insertion_point(field_unsafe_arena_release:CMsgChildProcessQueryResponse.gpu_topology)
  if (response_case() == kGpuTopology) {
    clear_has_response();
    auto* temp = _impl_.response_.gpu_topology_;
    _impl_.response_.gpu_topology_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void CMsgChildProcessQueryResponse::unsafe_arena_set_allocated_gpu_topology(
    ::CMsgChildProcessQueryGpuTopology* PROTOBUF_NULLABLE value) {
  // We rely on the oneof clear method to free the earlier contents
  // of this oneof. We can directly use the pointer we're given to
  // set the new value.
  clear_response();
  if (value) {
    set_has_gpu_topology();
    _impl_.response_.gpu_topology_ = value;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CMsgChildProcessQueryResponse.gpu_topology)
}
inline ::CMsgChildProcessQueryGpuTopology* PROTOBUF_NONNULL CMsgChildProcessQueryResponse::_internal_mutable_gpu_topology() {
  if (response_case() != kGpuTopology) {
    clear_response();
    set_has_gpu_topology();
    _impl_.response_.gpu_topology_ = 
        ::google::protobuf::Message::DefaultConstruct<::CMsgChildProcessQueryGpuTopology>(GetArena());
  }
  return _impl_.response_.gpu_topology_;
}
inline ::CMsgChildProcessQueryGpuTopology* PROTOBUF_NONNULL CMsgChildProcessQueryResponse::mutable_gpu_topology()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::CMsgChildProcessQueryGpuTopology* _msg = _internal_mutable_gpu_topology();
  // @@protoc_insertion_point(field_mutable:CMsgChildProcessQueryResponse.gpu_topology)
  return _msg;
}

inline bool CMsgChildProcessQueryResponse::has_response() const {
  return response_case() != RESPONSE_NOT_SET;
}
inline void CMsgChildProcessQueryResponse::clear_has_response() {
  _impl_._oneof_case_[0] = RESPONSE_NOT_SET;
}
inline CMsgChildProcessQueryResponse::ResponseCase CMsgChildProcessQueryResponse::response_case() const {
  return CMsgChildProcessQueryResponse::ResponseCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// CMsgChildProcessQueryGpuTopology_GpuInfo

// optional uint32 id = 1;
inline bool CMsgChildProcessQueryGpuTopology_GpuInfo::has_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t CMsgChildProcessQueryGpuTopology_GpuInfo::id() const {
  // @@protoc_insertion_point(field_get:CMsgChildProcessQueryGpuTopology.GpuInfo.id)
  return _internal_id();
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::set_id(::uint32_t value) {
  _internal_set_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CMsgChildProcessQueryGpuTopology.GpuInfo.id)
}
inline ::uint32_t CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_set_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// optional string name = 2;
inline bool CMsgChildProcessQueryGpuTopology_GpuInfo::has_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CMsgChildProcessQueryGpuTopology_GpuInfo::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CMsgChildProcessQueryGpuTopology.GpuInfo.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CMsgChildProcessQueryGpuTopology_GpuInfo::set_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CMsgChildProcessQueryGpuTopology.GpuInfo.name)
}
inline ::std::string* PROTOBUF_NONNULL CMsgChildProcessQueryGpuTopology_GpuInfo::mutable_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:CMsgChildProcessQueryGpuTopology.GpuInfo.name)
  return _s;
}
inline const ::std::string& CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_set_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CMsgChildProcessQueryGpuTopology_GpuInfo::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CMsgChildProcessQueryGpuTopology.GpuInfo.name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.name_.Set("", GetArena());
  }
  return released;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::set_allocated_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CMsgChildProcessQueryGpuTopology.GpuInfo.name)
}

// optional uint64 vram_size_bytes = 3;
inline bool CMsgChildProcessQueryGpuTopology_GpuInfo::has_vram_size_bytes() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::clear_vram_size_bytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vram_size_bytes_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint64_t CMsgChildProcessQueryGpuTopology_GpuInfo::vram_size_bytes() const {
  // @@protoc_insertion_point(field_get:CMsgChildProcessQueryGpuTopology.GpuInfo.vram_size_bytes)
  return _internal_vram_size_bytes();
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::set_vram_size_bytes(::uint64_t value) {
  _internal_set_vram_size_bytes(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:CMsgChildProcessQueryGpuTopology.GpuInfo.vram_size_bytes)
}
inline ::uint64_t CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_vram_size_bytes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.vram_size_bytes_;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_set_vram_size_bytes(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.vram_size_bytes_ = value;
}

// optional .EGpuDriverId driver_id = 4 [default = k_EGpuDriverId_Invalid];
inline bool CMsgChildProcessQueryGpuTopology_GpuInfo::has_driver_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::clear_driver_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.driver_id_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::EGpuDriverId CMsgChildProcessQueryGpuTopology_GpuInfo::driver_id() const {
  // @@protoc_insertion_point(field_get:CMsgChildProcessQueryGpuTopology.GpuInfo.driver_id)
  return _internal_driver_id();
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::set_driver_id(::EGpuDriverId value) {
  _internal_set_driver_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:CMsgChildProcessQueryGpuTopology.GpuInfo.driver_id)
}
inline ::EGpuDriverId CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_driver_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::EGpuDriverId>(_impl_.driver_id_);
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_set_driver_id(::EGpuDriverId value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::EGpuDriverId_internal_data_));
                                          _impl_.driver_id_ = value;
}

// optional int32 driver_version_major = 5;
inline bool CMsgChildProcessQueryGpuTopology_GpuInfo::has_driver_version_major() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::clear_driver_version_major() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.driver_version_major_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t CMsgChildProcessQueryGpuTopology_GpuInfo::driver_version_major() const {
  // @@protoc_insertion_point(field_get:CMsgChildProcessQueryGpuTopology.GpuInfo.driver_version_major)
  return _internal_driver_version_major();
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::set_driver_version_major(::int32_t value) {
  _internal_set_driver_version_major(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:CMsgChildProcessQueryGpuTopology.GpuInfo.driver_version_major)
}
inline ::int32_t CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_driver_version_major() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.driver_version_major_;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_set_driver_version_major(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.driver_version_major_ = value;
}

// optional int32 driver_version_minor = 6;
inline bool CMsgChildProcessQueryGpuTopology_GpuInfo::has_driver_version_minor() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::clear_driver_version_minor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.driver_version_minor_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::int32_t CMsgChildProcessQueryGpuTopology_GpuInfo::driver_version_minor() const {
  // @@protoc_insertion_point(field_get:CMsgChildProcessQueryGpuTopology.GpuInfo.driver_version_minor)
  return _internal_driver_version_minor();
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::set_driver_version_minor(::int32_t value) {
  _internal_set_driver_version_minor(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:CMsgChildProcessQueryGpuTopology.GpuInfo.driver_version_minor)
}
inline ::int32_t CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_driver_version_minor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.driver_version_minor_;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_set_driver_version_minor(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.driver_version_minor_ = value;
}

// optional int32 driver_version_patch = 7;
inline bool CMsgChildProcessQueryGpuTopology_GpuInfo::has_driver_version_patch() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::clear_driver_version_patch() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.driver_version_patch_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::int32_t CMsgChildProcessQueryGpuTopology_GpuInfo::driver_version_patch() const {
  // @@protoc_insertion_point(field_get:CMsgChildProcessQueryGpuTopology.GpuInfo.driver_version_patch)
  return _internal_driver_version_patch();
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::set_driver_version_patch(::int32_t value) {
  _internal_set_driver_version_patch(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:CMsgChildProcessQueryGpuTopology.GpuInfo.driver_version_patch)
}
inline ::int32_t CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_driver_version_patch() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.driver_version_patch_;
}
inline void CMsgChildProcessQueryGpuTopology_GpuInfo::_internal_set_driver_version_patch(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.driver_version_patch_ = value;
}

// -------------------------------------------------------------------

// CMsgChildProcessQueryGpuTopology

// repeated .CMsgChildProcessQueryGpuTopology.GpuInfo gpus = 1;
inline int CMsgChildProcessQueryGpuTopology::_internal_gpus_size() const {
  return _internal_gpus().size();
}
inline int CMsgChildProcessQueryGpuTopology::gpus_size() const {
  return _internal_gpus_size();
}
inline void CMsgChildProcessQueryGpuTopology::clear_gpus() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gpus_.Clear();
  ClearHasBitForRepeated(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::CMsgChildProcessQueryGpuTopology_GpuInfo* PROTOBUF_NONNULL CMsgChildProcessQueryGpuTopology::mutable_gpus(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:CMsgChildProcessQueryGpuTopology.gpus)
  return _internal_mutable_gpus()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::CMsgChildProcessQueryGpuTopology_GpuInfo>* PROTOBUF_NONNULL CMsgChildProcessQueryGpuTopology::mutable_gpus()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_mutable_list:CMsgChildProcessQueryGpuTopology.gpus)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_gpus();
}
inline const ::CMsgChildProcessQueryGpuTopology_GpuInfo& CMsgChildProcessQueryGpuTopology::gpus(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CMsgChildProcessQueryGpuTopology.gpus)
  return _internal_gpus().Get(index);
}
inline ::CMsgChildProcessQueryGpuTopology_GpuInfo* PROTOBUF_NONNULL CMsgChildProcessQueryGpuTopology::add_gpus()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::CMsgChildProcessQueryGpuTopology_GpuInfo* _add =
      _internal_mutable_gpus()->InternalAddWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), GetArena());
  SetHasBitForRepeated(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_add:CMsgChildProcessQueryGpuTopology.gpus)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::CMsgChildProcessQueryGpuTopology_GpuInfo>& CMsgChildProcessQueryGpuTopology::gpus() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:CMsgChildProcessQueryGpuTopology.gpus)
  return _internal_gpus();
}
inline const ::google::protobuf::RepeatedPtrField<::CMsgChildProcessQueryGpuTopology_GpuInfo>&
CMsgChildProcessQueryGpuTopology::_internal_gpus() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gpus_;
}
inline ::google::protobuf::RepeatedPtrField<::CMsgChildProcessQueryGpuTopology_GpuInfo>* PROTOBUF_NONNULL
CMsgChildProcessQueryGpuTopology::_internal_mutable_gpus() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.gpus_;
}

// optional uint32 default_gpu_id = 2;
inline bool CMsgChildProcessQueryGpuTopology::has_default_gpu_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CMsgChildProcessQueryGpuTopology::clear_default_gpu_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.default_gpu_id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t CMsgChildProcessQueryGpuTopology::default_gpu_id() const {
  // @@protoc_insertion_point(field_get:CMsgChildProcessQueryGpuTopology.default_gpu_id)
  return _internal_default_gpu_id();
}
inline void CMsgChildProcessQueryGpuTopology::set_default_gpu_id(::uint32_t value) {
  _internal_set_default_gpu_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CMsgChildProcessQueryGpuTopology.default_gpu_id)
}
inline ::uint32_t CMsgChildProcessQueryGpuTopology::_internal_default_gpu_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.default_gpu_id_;
}
inline void CMsgChildProcessQueryGpuTopology::_internal_set_default_gpu_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.default_gpu_id_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // steammessages_5fchildprocessquery_2eproto_2epb_2eh
