// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: steammessages_lobbymatchmaking.proto
// Protobuf C++ Version: 6.33.5

#ifndef steammessages_5flobbymatchmaking_2eproto_2epb_2eh
#define steammessages_5flobbymatchmaking_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "steammessages_base.pb.h"
#include "steammessages_unified_base.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_steammessages_5flobbymatchmaking_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_steammessages_5flobbymatchmaking_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_steammessages_5flobbymatchmaking_2eproto;
}  // extern "C"
enum ELobbyStatus : int;
extern const uint32_t ELobbyStatus_internal_data_[];
class LobbyMatchmakingLegacy_GetLobbyStatus_Request;
struct LobbyMatchmakingLegacy_GetLobbyStatus_RequestDefaultTypeInternal;
extern LobbyMatchmakingLegacy_GetLobbyStatus_RequestDefaultTypeInternal _LobbyMatchmakingLegacy_GetLobbyStatus_Request_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull LobbyMatchmakingLegacy_GetLobbyStatus_Request_class_data_;
class LobbyMatchmakingLegacy_GetLobbyStatus_Response;
struct LobbyMatchmakingLegacy_GetLobbyStatus_ResponseDefaultTypeInternal;
extern LobbyMatchmakingLegacy_GetLobbyStatus_ResponseDefaultTypeInternal _LobbyMatchmakingLegacy_GetLobbyStatus_Response_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull LobbyMatchmakingLegacy_GetLobbyStatus_Response_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::ELobbyStatus_internal_data_>
    internal::EnumTraitsImpl::value<::ELobbyStatus>;
}  // namespace protobuf
}  // namespace google

enum ELobbyStatus : int {
  k_ELobbyStatusInvalid = 0,
  k_ELobbyStatusExists = 1,
  k_ELobbyStatusDoesNotExist = 2,
  k_ELobbyStatusNotAMember = 3,
};

extern const uint32_t ELobbyStatus_internal_data_[];
inline constexpr ELobbyStatus ELobbyStatus_MIN =
    static_cast<ELobbyStatus>(0);
inline constexpr ELobbyStatus ELobbyStatus_MAX =
    static_cast<ELobbyStatus>(3);
inline bool ELobbyStatus_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int ELobbyStatus_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL ELobbyStatus_descriptor();
template <typename T>
const ::std::string& ELobbyStatus_Name(T value) {
  static_assert(::std::is_same<T, ELobbyStatus>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to ELobbyStatus_Name().");
  return ELobbyStatus_Name(static_cast<ELobbyStatus>(value));
}
template <>
inline const ::std::string& ELobbyStatus_Name(ELobbyStatus value) {
  return ::google::protobuf::internal::NameOfDenseEnum<ELobbyStatus_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool ELobbyStatus_Parse(
    ::absl::string_view name, ELobbyStatus* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<ELobbyStatus>(ELobbyStatus_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class LobbyMatchmakingLegacy_GetLobbyStatus_Response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:LobbyMatchmakingLegacy_GetLobbyStatus_Response) */ {
 public:
  inline LobbyMatchmakingLegacy_GetLobbyStatus_Response() : LobbyMatchmakingLegacy_GetLobbyStatus_Response(nullptr) {}
  ~LobbyMatchmakingLegacy_GetLobbyStatus_Response() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LobbyMatchmakingLegacy_GetLobbyStatus_Response* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LobbyMatchmakingLegacy_GetLobbyStatus_Response));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LobbyMatchmakingLegacy_GetLobbyStatus_Response(::google::protobuf::internal::ConstantInitialized);

  inline LobbyMatchmakingLegacy_GetLobbyStatus_Response(const LobbyMatchmakingLegacy_GetLobbyStatus_Response& from) : LobbyMatchmakingLegacy_GetLobbyStatus_Response(nullptr, from) {}
  inline LobbyMatchmakingLegacy_GetLobbyStatus_Response(LobbyMatchmakingLegacy_GetLobbyStatus_Response&& from) noexcept
      : LobbyMatchmakingLegacy_GetLobbyStatus_Response(nullptr, ::std::move(from)) {}
  inline LobbyMatchmakingLegacy_GetLobbyStatus_Response& operator=(const LobbyMatchmakingLegacy_GetLobbyStatus_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline LobbyMatchmakingLegacy_GetLobbyStatus_Response& operator=(LobbyMatchmakingLegacy_GetLobbyStatus_Response&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LobbyMatchmakingLegacy_GetLobbyStatus_Response& default_instance() {
    return *reinterpret_cast<const LobbyMatchmakingLegacy_GetLobbyStatus_Response*>(
        &_LobbyMatchmakingLegacy_GetLobbyStatus_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(LobbyMatchmakingLegacy_GetLobbyStatus_Response& a, LobbyMatchmakingLegacy_GetLobbyStatus_Response& b) { a.Swap(&b); }
  inline void Swap(LobbyMatchmakingLegacy_GetLobbyStatus_Response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LobbyMatchmakingLegacy_GetLobbyStatus_Response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LobbyMatchmakingLegacy_GetLobbyStatus_Response* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LobbyMatchmakingLegacy_GetLobbyStatus_Response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LobbyMatchmakingLegacy_GetLobbyStatus_Response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LobbyMatchmakingLegacy_GetLobbyStatus_Response& from) { LobbyMatchmakingLegacy_GetLobbyStatus_Response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LobbyMatchmakingLegacy_GetLobbyStatus_Response* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "LobbyMatchmakingLegacy_GetLobbyStatus_Response"; }

  explicit LobbyMatchmakingLegacy_GetLobbyStatus_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  LobbyMatchmakingLegacy_GetLobbyStatus_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LobbyMatchmakingLegacy_GetLobbyStatus_Response& from);
  LobbyMatchmakingLegacy_GetLobbyStatus_Response(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, LobbyMatchmakingLegacy_GetLobbyStatus_Response&& from) noexcept
      : LobbyMatchmakingLegacy_GetLobbyStatus_Response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSteamidLobbyFieldNumber = 2,
    kAppIdFieldNumber = 1,
    kLobbyStatusFieldNumber = 3,
  };
  // optional fixed64 steamid_lobby = 2;
  bool has_steamid_lobby() const;
  void clear_steamid_lobby() ;
  ::uint64_t steamid_lobby() const;
  void set_steamid_lobby(::uint64_t value);

  private:
  ::uint64_t _internal_steamid_lobby() const;
  void _internal_set_steamid_lobby(::uint64_t value);

  public:
  // optional uint32 app_id = 1;
  bool has_app_id() const;
  void clear_app_id() ;
  ::uint32_t app_id() const;
  void set_app_id(::uint32_t value);

  private:
  ::uint32_t _internal_app_id() const;
  void _internal_set_app_id(::uint32_t value);

  public:
  // optional .ELobbyStatus lobby_status = 3 [default = k_ELobbyStatusInvalid];
  bool has_lobby_status() const;
  void clear_lobby_status() ;
  ::ELobbyStatus lobby_status() const;
  void set_lobby_status(::ELobbyStatus value);

  private:
  ::ELobbyStatus _internal_lobby_status() const;
  void _internal_set_lobby_status(::ELobbyStatus value);

  public:
  // @@protoc_insertion_point(class_scope:LobbyMatchmakingLegacy_GetLobbyStatus_Response)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const LobbyMatchmakingLegacy_GetLobbyStatus_Response& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t steamid_lobby_;
    ::uint32_t app_id_;
    int lobby_status_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5flobbymatchmaking_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull LobbyMatchmakingLegacy_GetLobbyStatus_Response_class_data_;
// -------------------------------------------------------------------

class LobbyMatchmakingLegacy_GetLobbyStatus_Request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:LobbyMatchmakingLegacy_GetLobbyStatus_Request) */ {
 public:
  inline LobbyMatchmakingLegacy_GetLobbyStatus_Request() : LobbyMatchmakingLegacy_GetLobbyStatus_Request(nullptr) {}
  ~LobbyMatchmakingLegacy_GetLobbyStatus_Request() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LobbyMatchmakingLegacy_GetLobbyStatus_Request* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LobbyMatchmakingLegacy_GetLobbyStatus_Request));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LobbyMatchmakingLegacy_GetLobbyStatus_Request(::google::protobuf::internal::ConstantInitialized);

  inline LobbyMatchmakingLegacy_GetLobbyStatus_Request(const LobbyMatchmakingLegacy_GetLobbyStatus_Request& from) : LobbyMatchmakingLegacy_GetLobbyStatus_Request(nullptr, from) {}
  inline LobbyMatchmakingLegacy_GetLobbyStatus_Request(LobbyMatchmakingLegacy_GetLobbyStatus_Request&& from) noexcept
      : LobbyMatchmakingLegacy_GetLobbyStatus_Request(nullptr, ::std::move(from)) {}
  inline LobbyMatchmakingLegacy_GetLobbyStatus_Request& operator=(const LobbyMatchmakingLegacy_GetLobbyStatus_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline LobbyMatchmakingLegacy_GetLobbyStatus_Request& operator=(LobbyMatchmakingLegacy_GetLobbyStatus_Request&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LobbyMatchmakingLegacy_GetLobbyStatus_Request& default_instance() {
    return *reinterpret_cast<const LobbyMatchmakingLegacy_GetLobbyStatus_Request*>(
        &_LobbyMatchmakingLegacy_GetLobbyStatus_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(LobbyMatchmakingLegacy_GetLobbyStatus_Request& a, LobbyMatchmakingLegacy_GetLobbyStatus_Request& b) { a.Swap(&b); }
  inline void Swap(LobbyMatchmakingLegacy_GetLobbyStatus_Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LobbyMatchmakingLegacy_GetLobbyStatus_Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LobbyMatchmakingLegacy_GetLobbyStatus_Request* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LobbyMatchmakingLegacy_GetLobbyStatus_Request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LobbyMatchmakingLegacy_GetLobbyStatus_Request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LobbyMatchmakingLegacy_GetLobbyStatus_Request& from) { LobbyMatchmakingLegacy_GetLobbyStatus_Request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LobbyMatchmakingLegacy_GetLobbyStatus_Request* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "LobbyMatchmakingLegacy_GetLobbyStatus_Request"; }

  explicit LobbyMatchmakingLegacy_GetLobbyStatus_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  LobbyMatchmakingLegacy_GetLobbyStatus_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const LobbyMatchmakingLegacy_GetLobbyStatus_Request& from);
  LobbyMatchmakingLegacy_GetLobbyStatus_Request(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, LobbyMatchmakingLegacy_GetLobbyStatus_Request&& from) noexcept
      : LobbyMatchmakingLegacy_GetLobbyStatus_Request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSteamidLobbyFieldNumber = 2,
    kAppIdFieldNumber = 1,
    kClaimOwnershipFieldNumber = 3,
    kClaimMembershipFieldNumber = 4,
    kVersionNumFieldNumber = 5,
  };
  // optional fixed64 steamid_lobby = 2;
  bool has_steamid_lobby() const;
  void clear_steamid_lobby() ;
  ::uint64_t steamid_lobby() const;
  void set_steamid_lobby(::uint64_t value);

  private:
  ::uint64_t _internal_steamid_lobby() const;
  void _internal_set_steamid_lobby(::uint64_t value);

  public:
  // optional uint32 app_id = 1;
  bool has_app_id() const;
  void clear_app_id() ;
  ::uint32_t app_id() const;
  void set_app_id(::uint32_t value);

  private:
  ::uint32_t _internal_app_id() const;
  void _internal_set_app_id(::uint32_t value);

  public:
  // optional bool claim_ownership = 3;
  bool has_claim_ownership() const;
  void clear_claim_ownership() ;
  bool claim_ownership() const;
  void set_claim_ownership(bool value);

  private:
  bool _internal_claim_ownership() const;
  void _internal_set_claim_ownership(bool value);

  public:
  // optional bool claim_membership = 4;
  bool has_claim_membership() const;
  void clear_claim_membership() ;
  bool claim_membership() const;
  void set_claim_membership(bool value);

  private:
  bool _internal_claim_membership() const;
  void _internal_set_claim_membership(bool value);

  public:
  // optional uint32 version_num = 5;
  bool has_version_num() const;
  void clear_version_num() ;
  ::uint32_t version_num() const;
  void set_version_num(::uint32_t value);

  private:
  ::uint32_t _internal_version_num() const;
  void _internal_set_version_num(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:LobbyMatchmakingLegacy_GetLobbyStatus_Request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const LobbyMatchmakingLegacy_GetLobbyStatus_Request& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint64_t steamid_lobby_;
    ::uint32_t app_id_;
    bool claim_ownership_;
    bool claim_membership_;
    ::uint32_t version_num_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5flobbymatchmaking_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull LobbyMatchmakingLegacy_GetLobbyStatus_Request_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LobbyMatchmakingLegacy_GetLobbyStatus_Request

// optional uint32 app_id = 1;
inline bool LobbyMatchmakingLegacy_GetLobbyStatus_Request::has_app_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::clear_app_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t LobbyMatchmakingLegacy_GetLobbyStatus_Request::app_id() const {
  // @@protoc_insertion_point(field_get:LobbyMatchmakingLegacy_GetLobbyStatus_Request.app_id)
  return _internal_app_id();
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::set_app_id(::uint32_t value) {
  _internal_set_app_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:LobbyMatchmakingLegacy_GetLobbyStatus_Request.app_id)
}
inline ::uint32_t LobbyMatchmakingLegacy_GetLobbyStatus_Request::_internal_app_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.app_id_;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::_internal_set_app_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_id_ = value;
}

// optional fixed64 steamid_lobby = 2;
inline bool LobbyMatchmakingLegacy_GetLobbyStatus_Request::has_steamid_lobby() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::clear_steamid_lobby() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.steamid_lobby_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint64_t LobbyMatchmakingLegacy_GetLobbyStatus_Request::steamid_lobby() const {
  // @@protoc_insertion_point(field_get:LobbyMatchmakingLegacy_GetLobbyStatus_Request.steamid_lobby)
  return _internal_steamid_lobby();
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::set_steamid_lobby(::uint64_t value) {
  _internal_set_steamid_lobby(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:LobbyMatchmakingLegacy_GetLobbyStatus_Request.steamid_lobby)
}
inline ::uint64_t LobbyMatchmakingLegacy_GetLobbyStatus_Request::_internal_steamid_lobby() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.steamid_lobby_;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::_internal_set_steamid_lobby(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.steamid_lobby_ = value;
}

// optional bool claim_ownership = 3;
inline bool LobbyMatchmakingLegacy_GetLobbyStatus_Request::has_claim_ownership() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::clear_claim_ownership() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.claim_ownership_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline bool LobbyMatchmakingLegacy_GetLobbyStatus_Request::claim_ownership() const {
  // @@protoc_insertion_point(field_get:LobbyMatchmakingLegacy_GetLobbyStatus_Request.claim_ownership)
  return _internal_claim_ownership();
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::set_claim_ownership(bool value) {
  _internal_set_claim_ownership(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:LobbyMatchmakingLegacy_GetLobbyStatus_Request.claim_ownership)
}
inline bool LobbyMatchmakingLegacy_GetLobbyStatus_Request::_internal_claim_ownership() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.claim_ownership_;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::_internal_set_claim_ownership(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.claim_ownership_ = value;
}

// optional bool claim_membership = 4;
inline bool LobbyMatchmakingLegacy_GetLobbyStatus_Request::has_claim_membership() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::clear_claim_membership() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.claim_membership_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline bool LobbyMatchmakingLegacy_GetLobbyStatus_Request::claim_membership() const {
  // @@protoc_insertion_point(field_get:LobbyMatchmakingLegacy_GetLobbyStatus_Request.claim_membership)
  return _internal_claim_membership();
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::set_claim_membership(bool value) {
  _internal_set_claim_membership(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:LobbyMatchmakingLegacy_GetLobbyStatus_Request.claim_membership)
}
inline bool LobbyMatchmakingLegacy_GetLobbyStatus_Request::_internal_claim_membership() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.claim_membership_;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::_internal_set_claim_membership(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.claim_membership_ = value;
}

// optional uint32 version_num = 5;
inline bool LobbyMatchmakingLegacy_GetLobbyStatus_Request::has_version_num() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::clear_version_num() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.version_num_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t LobbyMatchmakingLegacy_GetLobbyStatus_Request::version_num() const {
  // @@protoc_insertion_point(field_get:LobbyMatchmakingLegacy_GetLobbyStatus_Request.version_num)
  return _internal_version_num();
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::set_version_num(::uint32_t value) {
  _internal_set_version_num(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:LobbyMatchmakingLegacy_GetLobbyStatus_Request.version_num)
}
inline ::uint32_t LobbyMatchmakingLegacy_GetLobbyStatus_Request::_internal_version_num() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.version_num_;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Request::_internal_set_version_num(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.version_num_ = value;
}

// -------------------------------------------------------------------

// LobbyMatchmakingLegacy_GetLobbyStatus_Response

// optional uint32 app_id = 1;
inline bool LobbyMatchmakingLegacy_GetLobbyStatus_Response::has_app_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Response::clear_app_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint32_t LobbyMatchmakingLegacy_GetLobbyStatus_Response::app_id() const {
  // @@protoc_insertion_point(field_get:LobbyMatchmakingLegacy_GetLobbyStatus_Response.app_id)
  return _internal_app_id();
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Response::set_app_id(::uint32_t value) {
  _internal_set_app_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:LobbyMatchmakingLegacy_GetLobbyStatus_Response.app_id)
}
inline ::uint32_t LobbyMatchmakingLegacy_GetLobbyStatus_Response::_internal_app_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.app_id_;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Response::_internal_set_app_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.app_id_ = value;
}

// optional fixed64 steamid_lobby = 2;
inline bool LobbyMatchmakingLegacy_GetLobbyStatus_Response::has_steamid_lobby() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Response::clear_steamid_lobby() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.steamid_lobby_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint64_t LobbyMatchmakingLegacy_GetLobbyStatus_Response::steamid_lobby() const {
  // @@protoc_insertion_point(field_get:LobbyMatchmakingLegacy_GetLobbyStatus_Response.steamid_lobby)
  return _internal_steamid_lobby();
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Response::set_steamid_lobby(::uint64_t value) {
  _internal_set_steamid_lobby(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:LobbyMatchmakingLegacy_GetLobbyStatus_Response.steamid_lobby)
}
inline ::uint64_t LobbyMatchmakingLegacy_GetLobbyStatus_Response::_internal_steamid_lobby() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.steamid_lobby_;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Response::_internal_set_steamid_lobby(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.steamid_lobby_ = value;
}

// optional .ELobbyStatus lobby_status = 3 [default = k_ELobbyStatusInvalid];
inline bool LobbyMatchmakingLegacy_GetLobbyStatus_Response::has_lobby_status() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Response::clear_lobby_status() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lobby_status_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::ELobbyStatus LobbyMatchmakingLegacy_GetLobbyStatus_Response::lobby_status() const {
  // @@protoc_insertion_point(field_get:LobbyMatchmakingLegacy_GetLobbyStatus_Response.lobby_status)
  return _internal_lobby_status();
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Response::set_lobby_status(::ELobbyStatus value) {
  _internal_set_lobby_status(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:LobbyMatchmakingLegacy_GetLobbyStatus_Response.lobby_status)
}
inline ::ELobbyStatus LobbyMatchmakingLegacy_GetLobbyStatus_Response::_internal_lobby_status() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::ELobbyStatus>(_impl_.lobby_status_);
}
inline void LobbyMatchmakingLegacy_GetLobbyStatus_Response::_internal_set_lobby_status(::ELobbyStatus value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::ELobbyStatus_internal_data_));
                                          _impl_.lobby_status_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::ELobbyStatus> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::ELobbyStatus>() {
  return ::ELobbyStatus_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // steammessages_5flobbymatchmaking_2eproto_2epb_2eh
