// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: steammessages_sitelicenseclient.proto
// Protobuf C++ Version: 6.33.5

#ifndef steammessages_5fsitelicenseclient_2eproto_2epb_2eh
#define steammessages_5fsitelicenseclient_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "steammessages_base.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_steammessages_5fsitelicenseclient_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_steammessages_5fsitelicenseclient_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_steammessages_5fsitelicenseclient_2eproto;
}  // extern "C"
class CMsgClientSiteInfo;
struct CMsgClientSiteInfoDefaultTypeInternal;
extern CMsgClientSiteInfoDefaultTypeInternal _CMsgClientSiteInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteInfo_class_data_;
class CMsgClientSiteLicenseCheckout;
struct CMsgClientSiteLicenseCheckoutDefaultTypeInternal;
extern CMsgClientSiteLicenseCheckoutDefaultTypeInternal _CMsgClientSiteLicenseCheckout_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteLicenseCheckout_class_data_;
class CMsgClientSiteLicenseCheckoutResponse;
struct CMsgClientSiteLicenseCheckoutResponseDefaultTypeInternal;
extern CMsgClientSiteLicenseCheckoutResponseDefaultTypeInternal _CMsgClientSiteLicenseCheckoutResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteLicenseCheckoutResponse_class_data_;
class CMsgClientSiteLicenseGetAvailableSeats;
struct CMsgClientSiteLicenseGetAvailableSeatsDefaultTypeInternal;
extern CMsgClientSiteLicenseGetAvailableSeatsDefaultTypeInternal _CMsgClientSiteLicenseGetAvailableSeats_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteLicenseGetAvailableSeats_class_data_;
class CMsgClientSiteLicenseGetAvailableSeatsResponse;
struct CMsgClientSiteLicenseGetAvailableSeatsResponseDefaultTypeInternal;
extern CMsgClientSiteLicenseGetAvailableSeatsResponseDefaultTypeInternal _CMsgClientSiteLicenseGetAvailableSeatsResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteLicenseGetAvailableSeatsResponse_class_data_;
class CMsgClientSiteLicenseGetContentCacheInfo;
struct CMsgClientSiteLicenseGetContentCacheInfoDefaultTypeInternal;
extern CMsgClientSiteLicenseGetContentCacheInfoDefaultTypeInternal _CMsgClientSiteLicenseGetContentCacheInfo_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteLicenseGetContentCacheInfo_class_data_;
class CMsgClientSiteLicenseGetContentCacheInfoResponse;
struct CMsgClientSiteLicenseGetContentCacheInfoResponseDefaultTypeInternal;
extern CMsgClientSiteLicenseGetContentCacheInfoResponseDefaultTypeInternal _CMsgClientSiteLicenseGetContentCacheInfoResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteLicenseGetContentCacheInfoResponse_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class CMsgClientSiteLicenseGetContentCacheInfoResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CMsgClientSiteLicenseGetContentCacheInfoResponse) */ {
 public:
  inline CMsgClientSiteLicenseGetContentCacheInfoResponse() : CMsgClientSiteLicenseGetContentCacheInfoResponse(nullptr) {}
  ~CMsgClientSiteLicenseGetContentCacheInfoResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgClientSiteLicenseGetContentCacheInfoResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgClientSiteLicenseGetContentCacheInfoResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CMsgClientSiteLicenseGetContentCacheInfoResponse(::google::protobuf::internal::ConstantInitialized);

  inline CMsgClientSiteLicenseGetContentCacheInfoResponse(const CMsgClientSiteLicenseGetContentCacheInfoResponse& from) : CMsgClientSiteLicenseGetContentCacheInfoResponse(nullptr, from) {}
  inline CMsgClientSiteLicenseGetContentCacheInfoResponse(CMsgClientSiteLicenseGetContentCacheInfoResponse&& from) noexcept
      : CMsgClientSiteLicenseGetContentCacheInfoResponse(nullptr, ::std::move(from)) {}
  inline CMsgClientSiteLicenseGetContentCacheInfoResponse& operator=(const CMsgClientSiteLicenseGetContentCacheInfoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgClientSiteLicenseGetContentCacheInfoResponse& operator=(CMsgClientSiteLicenseGetContentCacheInfoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgClientSiteLicenseGetContentCacheInfoResponse& default_instance() {
    return *reinterpret_cast<const CMsgClientSiteLicenseGetContentCacheInfoResponse*>(
        &_CMsgClientSiteLicenseGetContentCacheInfoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 6;
  friend void swap(CMsgClientSiteLicenseGetContentCacheInfoResponse& a, CMsgClientSiteLicenseGetContentCacheInfoResponse& b) { a.Swap(&b); }
  inline void Swap(CMsgClientSiteLicenseGetContentCacheInfoResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgClientSiteLicenseGetContentCacheInfoResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgClientSiteLicenseGetContentCacheInfoResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CMsgClientSiteLicenseGetContentCacheInfoResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CMsgClientSiteLicenseGetContentCacheInfoResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CMsgClientSiteLicenseGetContentCacheInfoResponse& from) { CMsgClientSiteLicenseGetContentCacheInfoResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgClientSiteLicenseGetContentCacheInfoResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgClientSiteLicenseGetContentCacheInfoResponse"; }

  explicit CMsgClientSiteLicenseGetContentCacheInfoResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgClientSiteLicenseGetContentCacheInfoResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgClientSiteLicenseGetContentCacheInfoResponse& from);
  CMsgClientSiteLicenseGetContentCacheInfoResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgClientSiteLicenseGetContentCacheInfoResponse&& from) noexcept
      : CMsgClientSiteLicenseGetContentCacheInfoResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIpAddressFieldNumber = 5,
    kUseCacheFieldNumber = 1,
    kIpv4AddressFieldNumber = 2,
    kPortNumberFieldNumber = 3,
    kP2PGroupFieldNumber = 4,
  };
  // optional string ip_address = 5;
  bool has_ip_address() const;
  void clear_ip_address() ;
  const ::std::string& ip_address() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_ip_address(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_ip_address();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_ip_address();
  void set_allocated_ip_address(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_ip_address() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_ip_address(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_ip_address();

  public:
  // optional bool use_cache = 1;
  bool has_use_cache() const;
  void clear_use_cache() ;
  bool use_cache() const;
  void set_use_cache(bool value);

  private:
  bool _internal_use_cache() const;
  void _internal_set_use_cache(bool value);

  public:
  // optional uint32 ipv4_address = 2;
  bool has_ipv4_address() const;
  void clear_ipv4_address() ;
  ::uint32_t ipv4_address() const;
  void set_ipv4_address(::uint32_t value);

  private:
  ::uint32_t _internal_ipv4_address() const;
  void _internal_set_ipv4_address(::uint32_t value);

  public:
  // optional uint32 port_number = 3;
  bool has_port_number() const;
  void clear_port_number() ;
  ::uint32_t port_number() const;
  void set_port_number(::uint32_t value);

  private:
  ::uint32_t _internal_port_number() const;
  void _internal_set_port_number(::uint32_t value);

  public:
  // optional uint32 p2p_group = 4;
  bool has_p2p_group() const;
  void clear_p2p_group() ;
  ::uint32_t p2p_group() const;
  void set_p2p_group(::uint32_t value);

  private:
  ::uint32_t _internal_p2p_group() const;
  void _internal_set_p2p_group(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgClientSiteLicenseGetContentCacheInfoResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgClientSiteLicenseGetContentCacheInfoResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr ip_address_;
    bool use_cache_;
    ::uint32_t ipv4_address_;
    ::uint32_t port_number_;
    ::uint32_t p2p_group_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5fsitelicenseclient_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteLicenseGetContentCacheInfoResponse_class_data_;
// -------------------------------------------------------------------

class CMsgClientSiteLicenseGetContentCacheInfo final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:CMsgClientSiteLicenseGetContentCacheInfo) */ {
 public:
  inline CMsgClientSiteLicenseGetContentCacheInfo() : CMsgClientSiteLicenseGetContentCacheInfo(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgClientSiteLicenseGetContentCacheInfo* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgClientSiteLicenseGetContentCacheInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CMsgClientSiteLicenseGetContentCacheInfo(::google::protobuf::internal::ConstantInitialized);

  inline CMsgClientSiteLicenseGetContentCacheInfo(const CMsgClientSiteLicenseGetContentCacheInfo& from) : CMsgClientSiteLicenseGetContentCacheInfo(nullptr, from) {}
  inline CMsgClientSiteLicenseGetContentCacheInfo(CMsgClientSiteLicenseGetContentCacheInfo&& from) noexcept
      : CMsgClientSiteLicenseGetContentCacheInfo(nullptr, ::std::move(from)) {}
  inline CMsgClientSiteLicenseGetContentCacheInfo& operator=(const CMsgClientSiteLicenseGetContentCacheInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgClientSiteLicenseGetContentCacheInfo& operator=(CMsgClientSiteLicenseGetContentCacheInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgClientSiteLicenseGetContentCacheInfo& default_instance() {
    return *reinterpret_cast<const CMsgClientSiteLicenseGetContentCacheInfo*>(
        &_CMsgClientSiteLicenseGetContentCacheInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(CMsgClientSiteLicenseGetContentCacheInfo& a, CMsgClientSiteLicenseGetContentCacheInfo& b) { a.Swap(&b); }
  inline void Swap(CMsgClientSiteLicenseGetContentCacheInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgClientSiteLicenseGetContentCacheInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgClientSiteLicenseGetContentCacheInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<CMsgClientSiteLicenseGetContentCacheInfo>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const CMsgClientSiteLicenseGetContentCacheInfo& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const CMsgClientSiteLicenseGetContentCacheInfo& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgClientSiteLicenseGetContentCacheInfo"; }

  explicit CMsgClientSiteLicenseGetContentCacheInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgClientSiteLicenseGetContentCacheInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgClientSiteLicenseGetContentCacheInfo& from);
  CMsgClientSiteLicenseGetContentCacheInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgClientSiteLicenseGetContentCacheInfo&& from) noexcept
      : CMsgClientSiteLicenseGetContentCacheInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:CMsgClientSiteLicenseGetContentCacheInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_steammessages_5fsitelicenseclient_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteLicenseGetContentCacheInfo_class_data_;
// -------------------------------------------------------------------

class CMsgClientSiteLicenseGetAvailableSeatsResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CMsgClientSiteLicenseGetAvailableSeatsResponse) */ {
 public:
  inline CMsgClientSiteLicenseGetAvailableSeatsResponse() : CMsgClientSiteLicenseGetAvailableSeatsResponse(nullptr) {}
  ~CMsgClientSiteLicenseGetAvailableSeatsResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgClientSiteLicenseGetAvailableSeatsResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgClientSiteLicenseGetAvailableSeatsResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CMsgClientSiteLicenseGetAvailableSeatsResponse(::google::protobuf::internal::ConstantInitialized);

  inline CMsgClientSiteLicenseGetAvailableSeatsResponse(const CMsgClientSiteLicenseGetAvailableSeatsResponse& from) : CMsgClientSiteLicenseGetAvailableSeatsResponse(nullptr, from) {}
  inline CMsgClientSiteLicenseGetAvailableSeatsResponse(CMsgClientSiteLicenseGetAvailableSeatsResponse&& from) noexcept
      : CMsgClientSiteLicenseGetAvailableSeatsResponse(nullptr, ::std::move(from)) {}
  inline CMsgClientSiteLicenseGetAvailableSeatsResponse& operator=(const CMsgClientSiteLicenseGetAvailableSeatsResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgClientSiteLicenseGetAvailableSeatsResponse& operator=(CMsgClientSiteLicenseGetAvailableSeatsResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgClientSiteLicenseGetAvailableSeatsResponse& default_instance() {
    return *reinterpret_cast<const CMsgClientSiteLicenseGetAvailableSeatsResponse*>(
        &_CMsgClientSiteLicenseGetAvailableSeatsResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(CMsgClientSiteLicenseGetAvailableSeatsResponse& a, CMsgClientSiteLicenseGetAvailableSeatsResponse& b) { a.Swap(&b); }
  inline void Swap(CMsgClientSiteLicenseGetAvailableSeatsResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgClientSiteLicenseGetAvailableSeatsResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgClientSiteLicenseGetAvailableSeatsResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CMsgClientSiteLicenseGetAvailableSeatsResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CMsgClientSiteLicenseGetAvailableSeatsResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CMsgClientSiteLicenseGetAvailableSeatsResponse& from) { CMsgClientSiteLicenseGetAvailableSeatsResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgClientSiteLicenseGetAvailableSeatsResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgClientSiteLicenseGetAvailableSeatsResponse"; }

  explicit CMsgClientSiteLicenseGetAvailableSeatsResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgClientSiteLicenseGetAvailableSeatsResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgClientSiteLicenseGetAvailableSeatsResponse& from);
  CMsgClientSiteLicenseGetAvailableSeatsResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgClientSiteLicenseGetAvailableSeatsResponse&& from) noexcept
      : CMsgClientSiteLicenseGetAvailableSeatsResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSeatsFieldNumber = 2,
    kEresultFieldNumber = 1,
  };
  // optional uint32 seats = 2;
  bool has_seats() const;
  void clear_seats() ;
  ::uint32_t seats() const;
  void set_seats(::uint32_t value);

  private:
  ::uint32_t _internal_seats() const;
  void _internal_set_seats(::uint32_t value);

  public:
  // optional int32 eresult = 1 [default = 2];
  bool has_eresult() const;
  void clear_eresult() ;
  ::int32_t eresult() const;
  void set_eresult(::int32_t value);

  private:
  ::int32_t _internal_eresult() const;
  void _internal_set_eresult(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgClientSiteLicenseGetAvailableSeatsResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgClientSiteLicenseGetAvailableSeatsResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t seats_;
    ::int32_t eresult_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5fsitelicenseclient_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteLicenseGetAvailableSeatsResponse_class_data_;
// -------------------------------------------------------------------

class CMsgClientSiteLicenseGetAvailableSeats final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CMsgClientSiteLicenseGetAvailableSeats) */ {
 public:
  inline CMsgClientSiteLicenseGetAvailableSeats() : CMsgClientSiteLicenseGetAvailableSeats(nullptr) {}
  ~CMsgClientSiteLicenseGetAvailableSeats() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgClientSiteLicenseGetAvailableSeats* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgClientSiteLicenseGetAvailableSeats));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CMsgClientSiteLicenseGetAvailableSeats(::google::protobuf::internal::ConstantInitialized);

  inline CMsgClientSiteLicenseGetAvailableSeats(const CMsgClientSiteLicenseGetAvailableSeats& from) : CMsgClientSiteLicenseGetAvailableSeats(nullptr, from) {}
  inline CMsgClientSiteLicenseGetAvailableSeats(CMsgClientSiteLicenseGetAvailableSeats&& from) noexcept
      : CMsgClientSiteLicenseGetAvailableSeats(nullptr, ::std::move(from)) {}
  inline CMsgClientSiteLicenseGetAvailableSeats& operator=(const CMsgClientSiteLicenseGetAvailableSeats& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgClientSiteLicenseGetAvailableSeats& operator=(CMsgClientSiteLicenseGetAvailableSeats&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgClientSiteLicenseGetAvailableSeats& default_instance() {
    return *reinterpret_cast<const CMsgClientSiteLicenseGetAvailableSeats*>(
        &_CMsgClientSiteLicenseGetAvailableSeats_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(CMsgClientSiteLicenseGetAvailableSeats& a, CMsgClientSiteLicenseGetAvailableSeats& b) { a.Swap(&b); }
  inline void Swap(CMsgClientSiteLicenseGetAvailableSeats* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgClientSiteLicenseGetAvailableSeats* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgClientSiteLicenseGetAvailableSeats* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CMsgClientSiteLicenseGetAvailableSeats>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CMsgClientSiteLicenseGetAvailableSeats& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CMsgClientSiteLicenseGetAvailableSeats& from) { CMsgClientSiteLicenseGetAvailableSeats::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgClientSiteLicenseGetAvailableSeats* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgClientSiteLicenseGetAvailableSeats"; }

  explicit CMsgClientSiteLicenseGetAvailableSeats(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgClientSiteLicenseGetAvailableSeats(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgClientSiteLicenseGetAvailableSeats& from);
  CMsgClientSiteLicenseGetAvailableSeats(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgClientSiteLicenseGetAvailableSeats&& from) noexcept
      : CMsgClientSiteLicenseGetAvailableSeats(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAppidFieldNumber = 1,
  };
  // optional uint32 appid = 1;
  bool has_appid() const;
  void clear_appid() ;
  ::uint32_t appid() const;
  void set_appid(::uint32_t value);

  private:
  ::uint32_t _internal_appid() const;
  void _internal_set_appid(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgClientSiteLicenseGetAvailableSeats)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgClientSiteLicenseGetAvailableSeats& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t appid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5fsitelicenseclient_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteLicenseGetAvailableSeats_class_data_;
// -------------------------------------------------------------------

class CMsgClientSiteLicenseCheckoutResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CMsgClientSiteLicenseCheckoutResponse) */ {
 public:
  inline CMsgClientSiteLicenseCheckoutResponse() : CMsgClientSiteLicenseCheckoutResponse(nullptr) {}
  ~CMsgClientSiteLicenseCheckoutResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgClientSiteLicenseCheckoutResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgClientSiteLicenseCheckoutResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CMsgClientSiteLicenseCheckoutResponse(::google::protobuf::internal::ConstantInitialized);

  inline CMsgClientSiteLicenseCheckoutResponse(const CMsgClientSiteLicenseCheckoutResponse& from) : CMsgClientSiteLicenseCheckoutResponse(nullptr, from) {}
  inline CMsgClientSiteLicenseCheckoutResponse(CMsgClientSiteLicenseCheckoutResponse&& from) noexcept
      : CMsgClientSiteLicenseCheckoutResponse(nullptr, ::std::move(from)) {}
  inline CMsgClientSiteLicenseCheckoutResponse& operator=(const CMsgClientSiteLicenseCheckoutResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgClientSiteLicenseCheckoutResponse& operator=(CMsgClientSiteLicenseCheckoutResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgClientSiteLicenseCheckoutResponse& default_instance() {
    return *reinterpret_cast<const CMsgClientSiteLicenseCheckoutResponse*>(
        &_CMsgClientSiteLicenseCheckoutResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CMsgClientSiteLicenseCheckoutResponse& a, CMsgClientSiteLicenseCheckoutResponse& b) { a.Swap(&b); }
  inline void Swap(CMsgClientSiteLicenseCheckoutResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgClientSiteLicenseCheckoutResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgClientSiteLicenseCheckoutResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CMsgClientSiteLicenseCheckoutResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CMsgClientSiteLicenseCheckoutResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CMsgClientSiteLicenseCheckoutResponse& from) { CMsgClientSiteLicenseCheckoutResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgClientSiteLicenseCheckoutResponse* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgClientSiteLicenseCheckoutResponse"; }

  explicit CMsgClientSiteLicenseCheckoutResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgClientSiteLicenseCheckoutResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgClientSiteLicenseCheckoutResponse& from);
  CMsgClientSiteLicenseCheckoutResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgClientSiteLicenseCheckoutResponse&& from) noexcept
      : CMsgClientSiteLicenseCheckoutResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kEresultFieldNumber = 1,
  };
  // optional int32 eresult = 1 [default = 2];
  bool has_eresult() const;
  void clear_eresult() ;
  ::int32_t eresult() const;
  void set_eresult(::int32_t value);

  private:
  ::int32_t _internal_eresult() const;
  void _internal_set_eresult(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgClientSiteLicenseCheckoutResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgClientSiteLicenseCheckoutResponse& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::int32_t eresult_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5fsitelicenseclient_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteLicenseCheckoutResponse_class_data_;
// -------------------------------------------------------------------

class CMsgClientSiteLicenseCheckout final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CMsgClientSiteLicenseCheckout) */ {
 public:
  inline CMsgClientSiteLicenseCheckout() : CMsgClientSiteLicenseCheckout(nullptr) {}
  ~CMsgClientSiteLicenseCheckout() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgClientSiteLicenseCheckout* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgClientSiteLicenseCheckout));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CMsgClientSiteLicenseCheckout(::google::protobuf::internal::ConstantInitialized);

  inline CMsgClientSiteLicenseCheckout(const CMsgClientSiteLicenseCheckout& from) : CMsgClientSiteLicenseCheckout(nullptr, from) {}
  inline CMsgClientSiteLicenseCheckout(CMsgClientSiteLicenseCheckout&& from) noexcept
      : CMsgClientSiteLicenseCheckout(nullptr, ::std::move(from)) {}
  inline CMsgClientSiteLicenseCheckout& operator=(const CMsgClientSiteLicenseCheckout& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgClientSiteLicenseCheckout& operator=(CMsgClientSiteLicenseCheckout&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgClientSiteLicenseCheckout& default_instance() {
    return *reinterpret_cast<const CMsgClientSiteLicenseCheckout*>(
        &_CMsgClientSiteLicenseCheckout_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CMsgClientSiteLicenseCheckout& a, CMsgClientSiteLicenseCheckout& b) { a.Swap(&b); }
  inline void Swap(CMsgClientSiteLicenseCheckout* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgClientSiteLicenseCheckout* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgClientSiteLicenseCheckout* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CMsgClientSiteLicenseCheckout>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CMsgClientSiteLicenseCheckout& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CMsgClientSiteLicenseCheckout& from) { CMsgClientSiteLicenseCheckout::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgClientSiteLicenseCheckout* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgClientSiteLicenseCheckout"; }

  explicit CMsgClientSiteLicenseCheckout(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgClientSiteLicenseCheckout(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgClientSiteLicenseCheckout& from);
  CMsgClientSiteLicenseCheckout(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgClientSiteLicenseCheckout&& from) noexcept
      : CMsgClientSiteLicenseCheckout(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kAppidFieldNumber = 1,
  };
  // optional uint32 appid = 1;
  bool has_appid() const;
  void clear_appid() ;
  ::uint32_t appid() const;
  void set_appid(::uint32_t value);

  private:
  ::uint32_t _internal_appid() const;
  void _internal_set_appid(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgClientSiteLicenseCheckout)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgClientSiteLicenseCheckout& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::uint32_t appid_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5fsitelicenseclient_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteLicenseCheckout_class_data_;
// -------------------------------------------------------------------

class CMsgClientSiteInfo final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CMsgClientSiteInfo) */ {
 public:
  inline CMsgClientSiteInfo() : CMsgClientSiteInfo(nullptr) {}
  ~CMsgClientSiteInfo() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CMsgClientSiteInfo* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CMsgClientSiteInfo));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CMsgClientSiteInfo(::google::protobuf::internal::ConstantInitialized);

  inline CMsgClientSiteInfo(const CMsgClientSiteInfo& from) : CMsgClientSiteInfo(nullptr, from) {}
  inline CMsgClientSiteInfo(CMsgClientSiteInfo&& from) noexcept
      : CMsgClientSiteInfo(nullptr, ::std::move(from)) {}
  inline CMsgClientSiteInfo& operator=(const CMsgClientSiteInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline CMsgClientSiteInfo& operator=(CMsgClientSiteInfo&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CMsgClientSiteInfo& default_instance() {
    return *reinterpret_cast<const CMsgClientSiteInfo*>(
        &_CMsgClientSiteInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CMsgClientSiteInfo& a, CMsgClientSiteInfo& b) { a.Swap(&b); }
  inline void Swap(CMsgClientSiteInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CMsgClientSiteInfo* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CMsgClientSiteInfo* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CMsgClientSiteInfo>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CMsgClientSiteInfo& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CMsgClientSiteInfo& from) { CMsgClientSiteInfo::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CMsgClientSiteInfo* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CMsgClientSiteInfo"; }

  explicit CMsgClientSiteInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CMsgClientSiteInfo(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CMsgClientSiteInfo& from);
  CMsgClientSiteInfo(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CMsgClientSiteInfo&& from) noexcept
      : CMsgClientSiteInfo(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSiteNameFieldNumber = 2,
    kSiteIdFieldNumber = 1,
    kAllowCachedCredentialsFieldNumber = 3,
  };
  // optional string site_name = 2;
  bool has_site_name() const;
  void clear_site_name() ;
  const ::std::string& site_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_site_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_site_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_site_name();
  void set_allocated_site_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_site_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_site_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_site_name();

  public:
  // optional uint64 site_id = 1;
  bool has_site_id() const;
  void clear_site_id() ;
  ::uint64_t site_id() const;
  void set_site_id(::uint64_t value);

  private:
  ::uint64_t _internal_site_id() const;
  void _internal_set_site_id(::uint64_t value);

  public:
  // optional bool allow_cached_credentials = 3;
  bool has_allow_cached_credentials() const;
  void clear_allow_cached_credentials() ;
  bool allow_cached_credentials() const;
  void set_allow_cached_credentials(bool value);

  private:
  bool _internal_allow_cached_credentials() const;
  void _internal_set_allow_cached_credentials(bool value);

  public:
  // @@protoc_insertion_point(class_scope:CMsgClientSiteInfo)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 3,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CMsgClientSiteInfo& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr site_name_;
    ::uint64_t site_id_;
    bool allow_cached_credentials_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5fsitelicenseclient_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CMsgClientSiteInfo_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CMsgClientSiteInfo

// optional uint64 site_id = 1;
inline bool CMsgClientSiteInfo::has_site_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CMsgClientSiteInfo::clear_site_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.site_id_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::uint64_t CMsgClientSiteInfo::site_id() const {
  // @@protoc_insertion_point(field_get:CMsgClientSiteInfo.site_id)
  return _internal_site_id();
}
inline void CMsgClientSiteInfo::set_site_id(::uint64_t value) {
  _internal_set_site_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CMsgClientSiteInfo.site_id)
}
inline ::uint64_t CMsgClientSiteInfo::_internal_site_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.site_id_;
}
inline void CMsgClientSiteInfo::_internal_set_site_id(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.site_id_ = value;
}

// optional string site_name = 2;
inline bool CMsgClientSiteInfo::has_site_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CMsgClientSiteInfo::clear_site_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.site_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CMsgClientSiteInfo::site_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CMsgClientSiteInfo.site_name)
  return _internal_site_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CMsgClientSiteInfo::set_site_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.site_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CMsgClientSiteInfo.site_name)
}
inline ::std::string* PROTOBUF_NONNULL CMsgClientSiteInfo::mutable_site_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_site_name();
  // @@protoc_insertion_point(field_mutable:CMsgClientSiteInfo.site_name)
  return _s;
}
inline const ::std::string& CMsgClientSiteInfo::_internal_site_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.site_name_.Get();
}
inline void CMsgClientSiteInfo::_internal_set_site_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.site_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CMsgClientSiteInfo::_internal_mutable_site_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.site_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CMsgClientSiteInfo::release_site_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CMsgClientSiteInfo.site_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.site_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.site_name_.Set("", GetArena());
  }
  return released;
}
inline void CMsgClientSiteInfo::set_allocated_site_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.site_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.site_name_.IsDefault()) {
    _impl_.site_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CMsgClientSiteInfo.site_name)
}

// optional bool allow_cached_credentials = 3;
inline bool CMsgClientSiteInfo::has_allow_cached_credentials() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void CMsgClientSiteInfo::clear_allow_cached_credentials() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.allow_cached_credentials_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline bool CMsgClientSiteInfo::allow_cached_credentials() const {
  // @@protoc_insertion_point(field_get:CMsgClientSiteInfo.allow_cached_credentials)
  return _internal_allow_cached_credentials();
}
inline void CMsgClientSiteInfo::set_allow_cached_credentials(bool value) {
  _internal_set_allow_cached_credentials(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:CMsgClientSiteInfo.allow_cached_credentials)
}
inline bool CMsgClientSiteInfo::_internal_allow_cached_credentials() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.allow_cached_credentials_;
}
inline void CMsgClientSiteInfo::_internal_set_allow_cached_credentials(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.allow_cached_credentials_ = value;
}

// -------------------------------------------------------------------

// CMsgClientSiteLicenseCheckout

// optional uint32 appid = 1;
inline bool CMsgClientSiteLicenseCheckout::has_appid() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CMsgClientSiteLicenseCheckout::clear_appid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.appid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t CMsgClientSiteLicenseCheckout::appid() const {
  // @@protoc_insertion_point(field_get:CMsgClientSiteLicenseCheckout.appid)
  return _internal_appid();
}
inline void CMsgClientSiteLicenseCheckout::set_appid(::uint32_t value) {
  _internal_set_appid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:CMsgClientSiteLicenseCheckout.appid)
}
inline ::uint32_t CMsgClientSiteLicenseCheckout::_internal_appid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.appid_;
}
inline void CMsgClientSiteLicenseCheckout::_internal_set_appid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.appid_ = value;
}

// -------------------------------------------------------------------

// CMsgClientSiteLicenseCheckoutResponse

// optional int32 eresult = 1 [default = 2];
inline bool CMsgClientSiteLicenseCheckoutResponse::has_eresult() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CMsgClientSiteLicenseCheckoutResponse::clear_eresult() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eresult_ = 2;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::int32_t CMsgClientSiteLicenseCheckoutResponse::eresult() const {
  // @@protoc_insertion_point(field_get:CMsgClientSiteLicenseCheckoutResponse.eresult)
  return _internal_eresult();
}
inline void CMsgClientSiteLicenseCheckoutResponse::set_eresult(::int32_t value) {
  _internal_set_eresult(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:CMsgClientSiteLicenseCheckoutResponse.eresult)
}
inline ::int32_t CMsgClientSiteLicenseCheckoutResponse::_internal_eresult() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.eresult_;
}
inline void CMsgClientSiteLicenseCheckoutResponse::_internal_set_eresult(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eresult_ = value;
}

// -------------------------------------------------------------------

// CMsgClientSiteLicenseGetAvailableSeats

// optional uint32 appid = 1;
inline bool CMsgClientSiteLicenseGetAvailableSeats::has_appid() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CMsgClientSiteLicenseGetAvailableSeats::clear_appid() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.appid_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t CMsgClientSiteLicenseGetAvailableSeats::appid() const {
  // @@protoc_insertion_point(field_get:CMsgClientSiteLicenseGetAvailableSeats.appid)
  return _internal_appid();
}
inline void CMsgClientSiteLicenseGetAvailableSeats::set_appid(::uint32_t value) {
  _internal_set_appid(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:CMsgClientSiteLicenseGetAvailableSeats.appid)
}
inline ::uint32_t CMsgClientSiteLicenseGetAvailableSeats::_internal_appid() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.appid_;
}
inline void CMsgClientSiteLicenseGetAvailableSeats::_internal_set_appid(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.appid_ = value;
}

// -------------------------------------------------------------------

// CMsgClientSiteLicenseGetAvailableSeatsResponse

// optional int32 eresult = 1 [default = 2];
inline bool CMsgClientSiteLicenseGetAvailableSeatsResponse::has_eresult() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CMsgClientSiteLicenseGetAvailableSeatsResponse::clear_eresult() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eresult_ = 2;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline ::int32_t CMsgClientSiteLicenseGetAvailableSeatsResponse::eresult() const {
  // @@protoc_insertion_point(field_get:CMsgClientSiteLicenseGetAvailableSeatsResponse.eresult)
  return _internal_eresult();
}
inline void CMsgClientSiteLicenseGetAvailableSeatsResponse::set_eresult(::int32_t value) {
  _internal_set_eresult(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CMsgClientSiteLicenseGetAvailableSeatsResponse.eresult)
}
inline ::int32_t CMsgClientSiteLicenseGetAvailableSeatsResponse::_internal_eresult() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.eresult_;
}
inline void CMsgClientSiteLicenseGetAvailableSeatsResponse::_internal_set_eresult(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.eresult_ = value;
}

// optional uint32 seats = 2;
inline bool CMsgClientSiteLicenseGetAvailableSeatsResponse::has_seats() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CMsgClientSiteLicenseGetAvailableSeatsResponse::clear_seats() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seats_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline ::uint32_t CMsgClientSiteLicenseGetAvailableSeatsResponse::seats() const {
  // @@protoc_insertion_point(field_get:CMsgClientSiteLicenseGetAvailableSeatsResponse.seats)
  return _internal_seats();
}
inline void CMsgClientSiteLicenseGetAvailableSeatsResponse::set_seats(::uint32_t value) {
  _internal_set_seats(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  // @@protoc_insertion_point(field_set:CMsgClientSiteLicenseGetAvailableSeatsResponse.seats)
}
inline ::uint32_t CMsgClientSiteLicenseGetAvailableSeatsResponse::_internal_seats() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.seats_;
}
inline void CMsgClientSiteLicenseGetAvailableSeatsResponse::_internal_set_seats(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.seats_ = value;
}

// -------------------------------------------------------------------

// CMsgClientSiteLicenseGetContentCacheInfo

// -------------------------------------------------------------------

// CMsgClientSiteLicenseGetContentCacheInfoResponse

// optional bool use_cache = 1;
inline bool CMsgClientSiteLicenseGetContentCacheInfoResponse::has_use_cache() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::clear_use_cache() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.use_cache_ = false;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline bool CMsgClientSiteLicenseGetContentCacheInfoResponse::use_cache() const {
  // @@protoc_insertion_point(field_get:CMsgClientSiteLicenseGetContentCacheInfoResponse.use_cache)
  return _internal_use_cache();
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::set_use_cache(bool value) {
  _internal_set_use_cache(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  // @@protoc_insertion_point(field_set:CMsgClientSiteLicenseGetContentCacheInfoResponse.use_cache)
}
inline bool CMsgClientSiteLicenseGetContentCacheInfoResponse::_internal_use_cache() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.use_cache_;
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::_internal_set_use_cache(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.use_cache_ = value;
}

// optional uint32 ipv4_address = 2;
inline bool CMsgClientSiteLicenseGetContentCacheInfoResponse::has_ipv4_address() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::clear_ipv4_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipv4_address_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::uint32_t CMsgClientSiteLicenseGetContentCacheInfoResponse::ipv4_address() const {
  // @@protoc_insertion_point(field_get:CMsgClientSiteLicenseGetContentCacheInfoResponse.ipv4_address)
  return _internal_ipv4_address();
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::set_ipv4_address(::uint32_t value) {
  _internal_set_ipv4_address(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:CMsgClientSiteLicenseGetContentCacheInfoResponse.ipv4_address)
}
inline ::uint32_t CMsgClientSiteLicenseGetContentCacheInfoResponse::_internal_ipv4_address() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ipv4_address_;
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::_internal_set_ipv4_address(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ipv4_address_ = value;
}

// optional uint32 port_number = 3;
inline bool CMsgClientSiteLicenseGetContentCacheInfoResponse::has_port_number() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::clear_port_number() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_number_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::uint32_t CMsgClientSiteLicenseGetContentCacheInfoResponse::port_number() const {
  // @@protoc_insertion_point(field_get:CMsgClientSiteLicenseGetContentCacheInfoResponse.port_number)
  return _internal_port_number();
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::set_port_number(::uint32_t value) {
  _internal_set_port_number(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:CMsgClientSiteLicenseGetContentCacheInfoResponse.port_number)
}
inline ::uint32_t CMsgClientSiteLicenseGetContentCacheInfoResponse::_internal_port_number() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.port_number_;
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::_internal_set_port_number(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.port_number_ = value;
}

// optional uint32 p2p_group = 4;
inline bool CMsgClientSiteLicenseGetContentCacheInfoResponse::has_p2p_group() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::clear_p2p_group() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.p2p_group_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::uint32_t CMsgClientSiteLicenseGetContentCacheInfoResponse::p2p_group() const {
  // @@protoc_insertion_point(field_get:CMsgClientSiteLicenseGetContentCacheInfoResponse.p2p_group)
  return _internal_p2p_group();
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::set_p2p_group(::uint32_t value) {
  _internal_set_p2p_group(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:CMsgClientSiteLicenseGetContentCacheInfoResponse.p2p_group)
}
inline ::uint32_t CMsgClientSiteLicenseGetContentCacheInfoResponse::_internal_p2p_group() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.p2p_group_;
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::_internal_set_p2p_group(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.p2p_group_ = value;
}

// optional string ip_address = 5;
inline bool CMsgClientSiteLicenseGetContentCacheInfoResponse::has_ip_address() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::clear_ip_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_address_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CMsgClientSiteLicenseGetContentCacheInfoResponse::ip_address() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CMsgClientSiteLicenseGetContentCacheInfoResponse.ip_address)
  return _internal_ip_address();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CMsgClientSiteLicenseGetContentCacheInfoResponse::set_ip_address(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.ip_address_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CMsgClientSiteLicenseGetContentCacheInfoResponse.ip_address)
}
inline ::std::string* PROTOBUF_NONNULL CMsgClientSiteLicenseGetContentCacheInfoResponse::mutable_ip_address()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_ip_address();
  // @@protoc_insertion_point(field_mutable:CMsgClientSiteLicenseGetContentCacheInfoResponse.ip_address)
  return _s;
}
inline const ::std::string& CMsgClientSiteLicenseGetContentCacheInfoResponse::_internal_ip_address() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ip_address_.Get();
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::_internal_set_ip_address(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ip_address_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CMsgClientSiteLicenseGetContentCacheInfoResponse::_internal_mutable_ip_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ip_address_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CMsgClientSiteLicenseGetContentCacheInfoResponse::release_ip_address() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CMsgClientSiteLicenseGetContentCacheInfoResponse.ip_address)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.ip_address_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ip_address_.Set("", GetArena());
  }
  return released;
}
inline void CMsgClientSiteLicenseGetContentCacheInfoResponse::set_allocated_ip_address(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.ip_address_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ip_address_.IsDefault()) {
    _impl_.ip_address_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CMsgClientSiteLicenseGetContentCacheInfoResponse.ip_address)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // steammessages_5fsitelicenseclient_2eproto_2epb_2eh
