// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: steammessages_secrets.proto
// Protobuf C++ Version: 6.33.5

#ifndef steammessages_5fsecrets_2eproto_2epb_2eh
#define steammessages_5fsecrets_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "steammessages_base.pb.h"
#include "steammessages_unified_base.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_steammessages_5fsecrets_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_steammessages_5fsecrets_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_steammessages_5fsecrets_2eproto;
}  // extern "C"
enum EKeyEscrowUsage : int;
extern const uint32_t EKeyEscrowUsage_internal_data_[];
class CKeyEscrow_Request;
struct CKeyEscrow_RequestDefaultTypeInternal;
extern CKeyEscrow_RequestDefaultTypeInternal _CKeyEscrow_Request_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CKeyEscrow_Request_class_data_;
class CKeyEscrow_Response;
struct CKeyEscrow_ResponseDefaultTypeInternal;
extern CKeyEscrow_ResponseDefaultTypeInternal _CKeyEscrow_Response_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CKeyEscrow_Response_class_data_;
class CKeyEscrow_Ticket;
struct CKeyEscrow_TicketDefaultTypeInternal;
extern CKeyEscrow_TicketDefaultTypeInternal _CKeyEscrow_Ticket_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull CKeyEscrow_Ticket_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::EKeyEscrowUsage_internal_data_>
    internal::EnumTraitsImpl::value<::EKeyEscrowUsage>;
}  // namespace protobuf
}  // namespace google

enum EKeyEscrowUsage : int {
  k_EKeyEscrowUsageStreamingDevice = 0,
};

extern const uint32_t EKeyEscrowUsage_internal_data_[];
inline constexpr EKeyEscrowUsage EKeyEscrowUsage_MIN =
    static_cast<EKeyEscrowUsage>(0);
inline constexpr EKeyEscrowUsage EKeyEscrowUsage_MAX =
    static_cast<EKeyEscrowUsage>(0);
inline bool EKeyEscrowUsage_IsValid(int value) {
  return 0 <= value && value <= 0;
}
inline constexpr int EKeyEscrowUsage_ARRAYSIZE = 0 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL EKeyEscrowUsage_descriptor();
template <typename T>
const ::std::string& EKeyEscrowUsage_Name(T value) {
  static_assert(::std::is_same<T, EKeyEscrowUsage>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EKeyEscrowUsage_Name().");
  return EKeyEscrowUsage_Name(static_cast<EKeyEscrowUsage>(value));
}
template <>
inline const ::std::string& EKeyEscrowUsage_Name(EKeyEscrowUsage value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EKeyEscrowUsage_descriptor, 0, 0>(
      static_cast<int>(value));
}
inline bool EKeyEscrowUsage_Parse(
    ::absl::string_view name, EKeyEscrowUsage* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<EKeyEscrowUsage>(EKeyEscrowUsage_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class CKeyEscrow_Ticket final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CKeyEscrow_Ticket) */ {
 public:
  inline CKeyEscrow_Ticket() : CKeyEscrow_Ticket(nullptr) {}
  ~CKeyEscrow_Ticket() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CKeyEscrow_Ticket* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CKeyEscrow_Ticket));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CKeyEscrow_Ticket(::google::protobuf::internal::ConstantInitialized);

  inline CKeyEscrow_Ticket(const CKeyEscrow_Ticket& from) : CKeyEscrow_Ticket(nullptr, from) {}
  inline CKeyEscrow_Ticket(CKeyEscrow_Ticket&& from) noexcept
      : CKeyEscrow_Ticket(nullptr, ::std::move(from)) {}
  inline CKeyEscrow_Ticket& operator=(const CKeyEscrow_Ticket& from) {
    CopyFrom(from);
    return *this;
  }
  inline CKeyEscrow_Ticket& operator=(CKeyEscrow_Ticket&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CKeyEscrow_Ticket& default_instance() {
    return *reinterpret_cast<const CKeyEscrow_Ticket*>(
        &_CKeyEscrow_Ticket_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(CKeyEscrow_Ticket& a, CKeyEscrow_Ticket& b) { a.Swap(&b); }
  inline void Swap(CKeyEscrow_Ticket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CKeyEscrow_Ticket* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CKeyEscrow_Ticket* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CKeyEscrow_Ticket>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CKeyEscrow_Ticket& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CKeyEscrow_Ticket& from) { CKeyEscrow_Ticket::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CKeyEscrow_Ticket* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CKeyEscrow_Ticket"; }

  explicit CKeyEscrow_Ticket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CKeyEscrow_Ticket(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CKeyEscrow_Ticket& from);
  CKeyEscrow_Ticket(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CKeyEscrow_Ticket&& from) noexcept
      : CKeyEscrow_Ticket(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPasswordFieldNumber = 1,
    kPayloadFieldNumber = 3,
    kDeviceNameFieldNumber = 6,
    kDeviceModelFieldNumber = 7,
    kDeviceSerialFieldNumber = 8,
    kIdentifierFieldNumber = 2,
    kTimestampFieldNumber = 4,
    kUsageFieldNumber = 5,
    kDeviceProvisioningIdFieldNumber = 9,
  };
  // optional bytes password = 1;
  bool has_password() const;
  void clear_password() ;
  const ::std::string& password() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_password(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_password();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_password();
  void set_allocated_password(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_password() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_password(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_password();

  public:
  // optional bytes payload = 3;
  bool has_payload() const;
  void clear_payload() ;
  const ::std::string& payload() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_payload(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_payload();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_payload();
  void set_allocated_payload(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_payload() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_payload(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_payload();

  public:
  // optional string device_name = 6;
  bool has_device_name() const;
  void clear_device_name() ;
  const ::std::string& device_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_device_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_device_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_device_name();
  void set_allocated_device_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_device_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_device_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_device_name();

  public:
  // optional string device_model = 7;
  bool has_device_model() const;
  void clear_device_model() ;
  const ::std::string& device_model() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_device_model(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_device_model();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_device_model();
  void set_allocated_device_model(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_device_model() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_device_model(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_device_model();

  public:
  // optional string device_serial = 8;
  bool has_device_serial() const;
  void clear_device_serial() ;
  const ::std::string& device_serial() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_device_serial(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_device_serial();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_device_serial();
  void set_allocated_device_serial(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_device_serial() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_device_serial(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_device_serial();

  public:
  // optional uint64 identifier = 2;
  bool has_identifier() const;
  void clear_identifier() ;
  ::uint64_t identifier() const;
  void set_identifier(::uint64_t value);

  private:
  ::uint64_t _internal_identifier() const;
  void _internal_set_identifier(::uint64_t value);

  public:
  // optional uint32 timestamp = 4;
  bool has_timestamp() const;
  void clear_timestamp() ;
  ::uint32_t timestamp() const;
  void set_timestamp(::uint32_t value);

  private:
  ::uint32_t _internal_timestamp() const;
  void _internal_set_timestamp(::uint32_t value);

  public:
  // optional .EKeyEscrowUsage usage = 5 [default = k_EKeyEscrowUsageStreamingDevice];
  bool has_usage() const;
  void clear_usage() ;
  ::EKeyEscrowUsage usage() const;
  void set_usage(::EKeyEscrowUsage value);

  private:
  ::EKeyEscrowUsage _internal_usage() const;
  void _internal_set_usage(::EKeyEscrowUsage value);

  public:
  // optional uint32 device_provisioning_id = 9;
  bool has_device_provisioning_id() const;
  void clear_device_provisioning_id() ;
  ::uint32_t device_provisioning_id() const;
  void set_device_provisioning_id(::uint32_t value);

  private:
  ::uint32_t _internal_device_provisioning_id() const;
  void _internal_set_device_provisioning_id(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:CKeyEscrow_Ticket)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 9,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CKeyEscrow_Ticket& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr password_;
    ::google::protobuf::internal::ArenaStringPtr payload_;
    ::google::protobuf::internal::ArenaStringPtr device_name_;
    ::google::protobuf::internal::ArenaStringPtr device_model_;
    ::google::protobuf::internal::ArenaStringPtr device_serial_;
    ::uint64_t identifier_;
    ::uint32_t timestamp_;
    int usage_;
    ::uint32_t device_provisioning_id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5fsecrets_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CKeyEscrow_Ticket_class_data_;
// -------------------------------------------------------------------

class CKeyEscrow_Request final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CKeyEscrow_Request) */ {
 public:
  inline CKeyEscrow_Request() : CKeyEscrow_Request(nullptr) {}
  ~CKeyEscrow_Request() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CKeyEscrow_Request* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CKeyEscrow_Request));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CKeyEscrow_Request(::google::protobuf::internal::ConstantInitialized);

  inline CKeyEscrow_Request(const CKeyEscrow_Request& from) : CKeyEscrow_Request(nullptr, from) {}
  inline CKeyEscrow_Request(CKeyEscrow_Request&& from) noexcept
      : CKeyEscrow_Request(nullptr, ::std::move(from)) {}
  inline CKeyEscrow_Request& operator=(const CKeyEscrow_Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline CKeyEscrow_Request& operator=(CKeyEscrow_Request&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CKeyEscrow_Request& default_instance() {
    return *reinterpret_cast<const CKeyEscrow_Request*>(
        &_CKeyEscrow_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(CKeyEscrow_Request& a, CKeyEscrow_Request& b) { a.Swap(&b); }
  inline void Swap(CKeyEscrow_Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CKeyEscrow_Request* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CKeyEscrow_Request* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CKeyEscrow_Request>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CKeyEscrow_Request& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CKeyEscrow_Request& from) { CKeyEscrow_Request::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CKeyEscrow_Request* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CKeyEscrow_Request"; }

  explicit CKeyEscrow_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CKeyEscrow_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CKeyEscrow_Request& from);
  CKeyEscrow_Request(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CKeyEscrow_Request&& from) noexcept
      : CKeyEscrow_Request(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRsaOaepShaTicketFieldNumber = 1,
    kPasswordFieldNumber = 2,
    kDeviceNameFieldNumber = 4,
    kUsageFieldNumber = 3,
  };
  // optional bytes rsa_oaep_sha_ticket = 1;
  bool has_rsa_oaep_sha_ticket() const;
  void clear_rsa_oaep_sha_ticket() ;
  const ::std::string& rsa_oaep_sha_ticket() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_rsa_oaep_sha_ticket(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_rsa_oaep_sha_ticket();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_rsa_oaep_sha_ticket();
  void set_allocated_rsa_oaep_sha_ticket(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_rsa_oaep_sha_ticket() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_rsa_oaep_sha_ticket(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_rsa_oaep_sha_ticket();

  public:
  // optional bytes password = 2;
  bool has_password() const;
  void clear_password() ;
  const ::std::string& password() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_password(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_password();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_password();
  void set_allocated_password(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_password() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_password(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_password();

  public:
  // optional string device_name = 4;
  bool has_device_name() const;
  void clear_device_name() ;
  const ::std::string& device_name() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_device_name(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_device_name();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_device_name();
  void set_allocated_device_name(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_device_name() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_device_name(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_device_name();

  public:
  // optional .EKeyEscrowUsage usage = 3 [default = k_EKeyEscrowUsageStreamingDevice];
  bool has_usage() const;
  void clear_usage() ;
  ::EKeyEscrowUsage usage() const;
  void set_usage(::EKeyEscrowUsage value);

  private:
  ::EKeyEscrowUsage _internal_usage() const;
  void _internal_set_usage(::EKeyEscrowUsage value);

  public:
  // @@protoc_insertion_point(class_scope:CKeyEscrow_Request)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CKeyEscrow_Request& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr rsa_oaep_sha_ticket_;
    ::google::protobuf::internal::ArenaStringPtr password_;
    ::google::protobuf::internal::ArenaStringPtr device_name_;
    int usage_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5fsecrets_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CKeyEscrow_Request_class_data_;
// -------------------------------------------------------------------

class CKeyEscrow_Response final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:CKeyEscrow_Response) */ {
 public:
  inline CKeyEscrow_Response() : CKeyEscrow_Response(nullptr) {}
  ~CKeyEscrow_Response() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(CKeyEscrow_Response* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(CKeyEscrow_Response));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR CKeyEscrow_Response(::google::protobuf::internal::ConstantInitialized);

  inline CKeyEscrow_Response(const CKeyEscrow_Response& from) : CKeyEscrow_Response(nullptr, from) {}
  inline CKeyEscrow_Response(CKeyEscrow_Response&& from) noexcept
      : CKeyEscrow_Response(nullptr, ::std::move(from)) {}
  inline CKeyEscrow_Response& operator=(const CKeyEscrow_Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline CKeyEscrow_Response& operator=(CKeyEscrow_Response&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const CKeyEscrow_Response& default_instance() {
    return *reinterpret_cast<const CKeyEscrow_Response*>(
        &_CKeyEscrow_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(CKeyEscrow_Response& a, CKeyEscrow_Response& b) { a.Swap(&b); }
  inline void Swap(CKeyEscrow_Response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(CKeyEscrow_Response* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  CKeyEscrow_Response* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<CKeyEscrow_Response>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const CKeyEscrow_Response& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const CKeyEscrow_Response& from) { CKeyEscrow_Response::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(CKeyEscrow_Response* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "CKeyEscrow_Response"; }

  explicit CKeyEscrow_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  CKeyEscrow_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CKeyEscrow_Response& from);
  CKeyEscrow_Response(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, CKeyEscrow_Response&& from) noexcept
      : CKeyEscrow_Response(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kTicketFieldNumber = 1,
  };
  // optional .CKeyEscrow_Ticket ticket = 1;
  bool has_ticket() const;
  void clear_ticket() ;
  const ::CKeyEscrow_Ticket& ticket() const;
  [[nodiscard]] ::CKeyEscrow_Ticket* PROTOBUF_NULLABLE release_ticket();
  ::CKeyEscrow_Ticket* PROTOBUF_NONNULL mutable_ticket();
  void set_allocated_ticket(::CKeyEscrow_Ticket* PROTOBUF_NULLABLE value);
  void unsafe_arena_set_allocated_ticket(::CKeyEscrow_Ticket* PROTOBUF_NULLABLE value);
  ::CKeyEscrow_Ticket* PROTOBUF_NULLABLE unsafe_arena_release_ticket();

  private:
  const ::CKeyEscrow_Ticket& _internal_ticket() const;
  ::CKeyEscrow_Ticket* PROTOBUF_NONNULL _internal_mutable_ticket();

  public:
  // @@protoc_insertion_point(class_scope:CKeyEscrow_Response)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 1,
                                   1, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const CKeyEscrow_Response& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::CKeyEscrow_Ticket* PROTOBUF_NULLABLE ticket_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_steammessages_5fsecrets_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull CKeyEscrow_Response_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// CKeyEscrow_Request

// optional bytes rsa_oaep_sha_ticket = 1;
inline bool CKeyEscrow_Request::has_rsa_oaep_sha_ticket() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CKeyEscrow_Request::clear_rsa_oaep_sha_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rsa_oaep_sha_ticket_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CKeyEscrow_Request::rsa_oaep_sha_ticket() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Request.rsa_oaep_sha_ticket)
  return _internal_rsa_oaep_sha_ticket();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CKeyEscrow_Request::set_rsa_oaep_sha_ticket(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.rsa_oaep_sha_ticket_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CKeyEscrow_Request.rsa_oaep_sha_ticket)
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Request::mutable_rsa_oaep_sha_ticket()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_rsa_oaep_sha_ticket();
  // @@protoc_insertion_point(field_mutable:CKeyEscrow_Request.rsa_oaep_sha_ticket)
  return _s;
}
inline const ::std::string& CKeyEscrow_Request::_internal_rsa_oaep_sha_ticket() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.rsa_oaep_sha_ticket_.Get();
}
inline void CKeyEscrow_Request::_internal_set_rsa_oaep_sha_ticket(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.rsa_oaep_sha_ticket_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Request::_internal_mutable_rsa_oaep_sha_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.rsa_oaep_sha_ticket_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CKeyEscrow_Request::release_rsa_oaep_sha_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CKeyEscrow_Request.rsa_oaep_sha_ticket)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.rsa_oaep_sha_ticket_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.rsa_oaep_sha_ticket_.Set("", GetArena());
  }
  return released;
}
inline void CKeyEscrow_Request::set_allocated_rsa_oaep_sha_ticket(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.rsa_oaep_sha_ticket_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.rsa_oaep_sha_ticket_.IsDefault()) {
    _impl_.rsa_oaep_sha_ticket_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CKeyEscrow_Request.rsa_oaep_sha_ticket)
}

// optional bytes password = 2;
inline bool CKeyEscrow_Request::has_password() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CKeyEscrow_Request::clear_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& CKeyEscrow_Request::password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Request.password)
  return _internal_password();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CKeyEscrow_Request::set_password(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.password_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CKeyEscrow_Request.password)
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Request::mutable_password()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:CKeyEscrow_Request.password)
  return _s;
}
inline const ::std::string& CKeyEscrow_Request::_internal_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.password_.Get();
}
inline void CKeyEscrow_Request::_internal_set_password(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Request::_internal_mutable_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.password_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CKeyEscrow_Request::release_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CKeyEscrow_Request.password)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.password_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.password_.Set("", GetArena());
  }
  return released;
}
inline void CKeyEscrow_Request::set_allocated_password(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CKeyEscrow_Request.password)
}

// optional .EKeyEscrowUsage usage = 3 [default = k_EKeyEscrowUsageStreamingDevice];
inline bool CKeyEscrow_Request::has_usage() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void CKeyEscrow_Request::clear_usage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.usage_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::EKeyEscrowUsage CKeyEscrow_Request::usage() const {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Request.usage)
  return _internal_usage();
}
inline void CKeyEscrow_Request::set_usage(::EKeyEscrowUsage value) {
  _internal_set_usage(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:CKeyEscrow_Request.usage)
}
inline ::EKeyEscrowUsage CKeyEscrow_Request::_internal_usage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::EKeyEscrowUsage>(_impl_.usage_);
}
inline void CKeyEscrow_Request::_internal_set_usage(::EKeyEscrowUsage value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::EKeyEscrowUsage_internal_data_));
                                          _impl_.usage_ = value;
}

// optional string device_name = 4;
inline bool CKeyEscrow_Request::has_device_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void CKeyEscrow_Request::clear_device_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& CKeyEscrow_Request::device_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Request.device_name)
  return _internal_device_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CKeyEscrow_Request::set_device_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.device_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CKeyEscrow_Request.device_name)
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Request::mutable_device_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_device_name();
  // @@protoc_insertion_point(field_mutable:CKeyEscrow_Request.device_name)
  return _s;
}
inline const ::std::string& CKeyEscrow_Request::_internal_device_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.device_name_.Get();
}
inline void CKeyEscrow_Request::_internal_set_device_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Request::_internal_mutable_device_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.device_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CKeyEscrow_Request::release_device_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CKeyEscrow_Request.device_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.device_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.device_name_.Set("", GetArena());
  }
  return released;
}
inline void CKeyEscrow_Request::set_allocated_device_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.device_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.device_name_.IsDefault()) {
    _impl_.device_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CKeyEscrow_Request.device_name)
}

// -------------------------------------------------------------------

// CKeyEscrow_Ticket

// optional bytes password = 1;
inline bool CKeyEscrow_Ticket::has_password() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void CKeyEscrow_Ticket::clear_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& CKeyEscrow_Ticket::password() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Ticket.password)
  return _internal_password();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CKeyEscrow_Ticket::set_password(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.password_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CKeyEscrow_Ticket.password)
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Ticket::mutable_password()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:CKeyEscrow_Ticket.password)
  return _s;
}
inline const ::std::string& CKeyEscrow_Ticket::_internal_password() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.password_.Get();
}
inline void CKeyEscrow_Ticket::_internal_set_password(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.password_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Ticket::_internal_mutable_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.password_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CKeyEscrow_Ticket::release_password() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CKeyEscrow_Ticket.password)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.password_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.password_.Set("", GetArena());
  }
  return released;
}
inline void CKeyEscrow_Ticket::set_allocated_password(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.password_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.password_.IsDefault()) {
    _impl_.password_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CKeyEscrow_Ticket.password)
}

// optional uint64 identifier = 2;
inline bool CKeyEscrow_Ticket::has_identifier() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000020U);
  return value;
}
inline void CKeyEscrow_Ticket::clear_identifier() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identifier_ = ::uint64_t{0u};
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000020U);
}
inline ::uint64_t CKeyEscrow_Ticket::identifier() const {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Ticket.identifier)
  return _internal_identifier();
}
inline void CKeyEscrow_Ticket::set_identifier(::uint64_t value) {
  _internal_set_identifier(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000020U);
  // @@protoc_insertion_point(field_set:CKeyEscrow_Ticket.identifier)
}
inline ::uint64_t CKeyEscrow_Ticket::_internal_identifier() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.identifier_;
}
inline void CKeyEscrow_Ticket::_internal_set_identifier(::uint64_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.identifier_ = value;
}

// optional bytes payload = 3;
inline bool CKeyEscrow_Ticket::has_payload() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void CKeyEscrow_Ticket::clear_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.payload_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& CKeyEscrow_Ticket::payload() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Ticket.payload)
  return _internal_payload();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CKeyEscrow_Ticket::set_payload(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.payload_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CKeyEscrow_Ticket.payload)
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Ticket::mutable_payload()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_payload();
  // @@protoc_insertion_point(field_mutable:CKeyEscrow_Ticket.payload)
  return _s;
}
inline const ::std::string& CKeyEscrow_Ticket::_internal_payload() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.payload_.Get();
}
inline void CKeyEscrow_Ticket::_internal_set_payload(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.payload_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Ticket::_internal_mutable_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.payload_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CKeyEscrow_Ticket::release_payload() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CKeyEscrow_Ticket.payload)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.payload_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.payload_.Set("", GetArena());
  }
  return released;
}
inline void CKeyEscrow_Ticket::set_allocated_payload(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.payload_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.payload_.IsDefault()) {
    _impl_.payload_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CKeyEscrow_Ticket.payload)
}

// optional uint32 timestamp = 4;
inline bool CKeyEscrow_Ticket::has_timestamp() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000040U);
  return value;
}
inline void CKeyEscrow_Ticket::clear_timestamp() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000040U);
}
inline ::uint32_t CKeyEscrow_Ticket::timestamp() const {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Ticket.timestamp)
  return _internal_timestamp();
}
inline void CKeyEscrow_Ticket::set_timestamp(::uint32_t value) {
  _internal_set_timestamp(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000040U);
  // @@protoc_insertion_point(field_set:CKeyEscrow_Ticket.timestamp)
}
inline ::uint32_t CKeyEscrow_Ticket::_internal_timestamp() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.timestamp_;
}
inline void CKeyEscrow_Ticket::_internal_set_timestamp(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.timestamp_ = value;
}

// optional .EKeyEscrowUsage usage = 5 [default = k_EKeyEscrowUsageStreamingDevice];
inline bool CKeyEscrow_Ticket::has_usage() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000080U);
  return value;
}
inline void CKeyEscrow_Ticket::clear_usage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.usage_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000080U);
}
inline ::EKeyEscrowUsage CKeyEscrow_Ticket::usage() const {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Ticket.usage)
  return _internal_usage();
}
inline void CKeyEscrow_Ticket::set_usage(::EKeyEscrowUsage value) {
  _internal_set_usage(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000080U);
  // @@protoc_insertion_point(field_set:CKeyEscrow_Ticket.usage)
}
inline ::EKeyEscrowUsage CKeyEscrow_Ticket::_internal_usage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::EKeyEscrowUsage>(_impl_.usage_);
}
inline void CKeyEscrow_Ticket::_internal_set_usage(::EKeyEscrowUsage value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);

                                          assert(::google::protobuf::internal::ValidateEnum(
                                              value, ::EKeyEscrowUsage_internal_data_));
                                          _impl_.usage_ = value;
}

// optional string device_name = 6;
inline bool CKeyEscrow_Ticket::has_device_name() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void CKeyEscrow_Ticket::clear_device_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_name_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline const ::std::string& CKeyEscrow_Ticket::device_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Ticket.device_name)
  return _internal_device_name();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CKeyEscrow_Ticket::set_device_name(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  _impl_.device_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CKeyEscrow_Ticket.device_name)
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Ticket::mutable_device_name()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  ::std::string* _s = _internal_mutable_device_name();
  // @@protoc_insertion_point(field_mutable:CKeyEscrow_Ticket.device_name)
  return _s;
}
inline const ::std::string& CKeyEscrow_Ticket::_internal_device_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.device_name_.Get();
}
inline void CKeyEscrow_Ticket::_internal_set_device_name(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_name_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Ticket::_internal_mutable_device_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.device_name_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CKeyEscrow_Ticket::release_device_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CKeyEscrow_Ticket.device_name)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000004U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  auto* released = _impl_.device_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.device_name_.Set("", GetArena());
  }
  return released;
}
inline void CKeyEscrow_Ticket::set_allocated_device_name(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
  }
  _impl_.device_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.device_name_.IsDefault()) {
    _impl_.device_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CKeyEscrow_Ticket.device_name)
}

// optional string device_model = 7;
inline bool CKeyEscrow_Ticket::has_device_model() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void CKeyEscrow_Ticket::clear_device_model() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_model_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline const ::std::string& CKeyEscrow_Ticket::device_model() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Ticket.device_model)
  return _internal_device_model();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CKeyEscrow_Ticket::set_device_model(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  _impl_.device_model_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CKeyEscrow_Ticket.device_model)
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Ticket::mutable_device_model()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  ::std::string* _s = _internal_mutable_device_model();
  // @@protoc_insertion_point(field_mutable:CKeyEscrow_Ticket.device_model)
  return _s;
}
inline const ::std::string& CKeyEscrow_Ticket::_internal_device_model() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.device_model_.Get();
}
inline void CKeyEscrow_Ticket::_internal_set_device_model(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_model_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Ticket::_internal_mutable_device_model() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.device_model_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CKeyEscrow_Ticket::release_device_model() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CKeyEscrow_Ticket.device_model)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000008U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  auto* released = _impl_.device_model_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.device_model_.Set("", GetArena());
  }
  return released;
}
inline void CKeyEscrow_Ticket::set_allocated_device_model(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
  }
  _impl_.device_model_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.device_model_.IsDefault()) {
    _impl_.device_model_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CKeyEscrow_Ticket.device_model)
}

// optional string device_serial = 8;
inline bool CKeyEscrow_Ticket::has_device_serial() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void CKeyEscrow_Ticket::clear_device_serial() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_serial_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline const ::std::string& CKeyEscrow_Ticket::device_serial() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Ticket.device_serial)
  return _internal_device_serial();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void CKeyEscrow_Ticket::set_device_serial(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  _impl_.device_serial_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:CKeyEscrow_Ticket.device_serial)
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Ticket::mutable_device_serial()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  ::std::string* _s = _internal_mutable_device_serial();
  // @@protoc_insertion_point(field_mutable:CKeyEscrow_Ticket.device_serial)
  return _s;
}
inline const ::std::string& CKeyEscrow_Ticket::_internal_device_serial() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.device_serial_.Get();
}
inline void CKeyEscrow_Ticket::_internal_set_device_serial(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_serial_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL CKeyEscrow_Ticket::_internal_mutable_device_serial() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.device_serial_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE CKeyEscrow_Ticket::release_device_serial() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CKeyEscrow_Ticket.device_serial)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000010U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  auto* released = _impl_.device_serial_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.device_serial_.Set("", GetArena());
  }
  return released;
}
inline void CKeyEscrow_Ticket::set_allocated_device_serial(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
  }
  _impl_.device_serial_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.device_serial_.IsDefault()) {
    _impl_.device_serial_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:CKeyEscrow_Ticket.device_serial)
}

// optional uint32 device_provisioning_id = 9;
inline bool CKeyEscrow_Ticket::has_device_provisioning_id() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000100U);
  return value;
}
inline void CKeyEscrow_Ticket::clear_device_provisioning_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_provisioning_id_ = 0u;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000100U);
}
inline ::uint32_t CKeyEscrow_Ticket::device_provisioning_id() const {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Ticket.device_provisioning_id)
  return _internal_device_provisioning_id();
}
inline void CKeyEscrow_Ticket::set_device_provisioning_id(::uint32_t value) {
  _internal_set_device_provisioning_id(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000100U);
  // @@protoc_insertion_point(field_set:CKeyEscrow_Ticket.device_provisioning_id)
}
inline ::uint32_t CKeyEscrow_Ticket::_internal_device_provisioning_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.device_provisioning_id_;
}
inline void CKeyEscrow_Ticket::_internal_set_device_provisioning_id(::uint32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.device_provisioning_id_ = value;
}

// -------------------------------------------------------------------

// CKeyEscrow_Response

// optional .CKeyEscrow_Ticket ticket = 1;
inline bool CKeyEscrow_Response::has_ticket() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  PROTOBUF_ASSUME(!value || _impl_.ticket_ != nullptr);
  return value;
}
inline void CKeyEscrow_Response::clear_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ticket_ != nullptr) _impl_.ticket_->Clear();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::CKeyEscrow_Ticket& CKeyEscrow_Response::_internal_ticket() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::CKeyEscrow_Ticket* p = _impl_.ticket_;
  return p != nullptr ? *p : reinterpret_cast<const ::CKeyEscrow_Ticket&>(::_CKeyEscrow_Ticket_default_instance_);
}
inline const ::CKeyEscrow_Ticket& CKeyEscrow_Response::ticket() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:CKeyEscrow_Response.ticket)
  return _internal_ticket();
}
inline void CKeyEscrow_Response::unsafe_arena_set_allocated_ticket(
    ::CKeyEscrow_Ticket* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.ticket_);
  }
  _impl_.ticket_ = reinterpret_cast<::CKeyEscrow_Ticket*>(value);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:CKeyEscrow_Response.ticket)
}
inline ::CKeyEscrow_Ticket* PROTOBUF_NULLABLE CKeyEscrow_Response::release_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::CKeyEscrow_Ticket* released = _impl_.ticket_;
  _impl_.ticket_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::CKeyEscrow_Ticket* PROTOBUF_NULLABLE CKeyEscrow_Response::unsafe_arena_release_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:CKeyEscrow_Response.ticket)

  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::CKeyEscrow_Ticket* temp = _impl_.ticket_;
  _impl_.ticket_ = nullptr;
  return temp;
}
inline ::CKeyEscrow_Ticket* PROTOBUF_NONNULL CKeyEscrow_Response::_internal_mutable_ticket() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.ticket_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::CKeyEscrow_Ticket>(GetArena());
    _impl_.ticket_ = reinterpret_cast<::CKeyEscrow_Ticket*>(p);
  }
  return _impl_.ticket_;
}
inline ::CKeyEscrow_Ticket* PROTOBUF_NONNULL CKeyEscrow_Response::mutable_ticket()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::CKeyEscrow_Ticket* _msg = _internal_mutable_ticket();
  // @@protoc_insertion_point(field_mutable:CKeyEscrow_Response.ticket)
  return _msg;
}
inline void CKeyEscrow_Response::set_allocated_ticket(::CKeyEscrow_Ticket* PROTOBUF_NULLABLE value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.ticket_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = value->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }

  _impl_.ticket_ = reinterpret_cast<::CKeyEscrow_Ticket*>(value);
  // @@protoc_insertion_point(field_set_allocated:CKeyEscrow_Response.ticket)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::EKeyEscrowUsage> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::EKeyEscrowUsage>() {
  return ::EKeyEscrowUsage_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // steammessages_5fsecrets_2eproto_2epb_2eh
