// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: webuimessages_achievements.proto
// Protobuf C++ Version: 6.33.5

#include "webuimessages_achievements.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;

inline constexpr CAchievements_GetInfo_Response_Info::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        desc_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        image_url_achieved_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        image_url_not_achieved_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        achieved_{false},
        unlock_time_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR CAchievements_GetInfo_Response_Info::CAchievements_GetInfo_Response_Info(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CAchievements_GetInfo_Response_Info_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CAchievements_GetInfo_Response_InfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CAchievements_GetInfo_Response_InfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CAchievements_GetInfo_Response_InfoDefaultTypeInternal() {}
  union {
    CAchievements_GetInfo_Response_Info _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CAchievements_GetInfo_Response_InfoDefaultTypeInternal _CAchievements_GetInfo_Response_Info_default_instance_;

inline constexpr CAchievements_GetInfo_Request::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        gameid_{::uint64_t{0u}} {}

template <typename>
PROTOBUF_CONSTEXPR CAchievements_GetInfo_Request::CAchievements_GetInfo_Request(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CAchievements_GetInfo_Request_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CAchievements_GetInfo_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CAchievements_GetInfo_RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CAchievements_GetInfo_RequestDefaultTypeInternal() {}
  union {
    CAchievements_GetInfo_Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CAchievements_GetInfo_RequestDefaultTypeInternal _CAchievements_GetInfo_Request_default_instance_;

inline constexpr CAchievements_GetInfo_Response::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        achievements_{} {}

template <typename>
PROTOBUF_CONSTEXPR CAchievements_GetInfo_Response::CAchievements_GetInfo_Response(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CAchievements_GetInfo_Response_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CAchievements_GetInfo_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CAchievements_GetInfo_ResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CAchievements_GetInfo_ResponseDefaultTypeInternal() {}
  union {
    CAchievements_GetInfo_Response _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CAchievements_GetInfo_ResponseDefaultTypeInternal _CAchievements_GetInfo_Response_default_instance_;
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_webuimessages_5fachievements_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_webuimessages_5fachievements_2eproto = nullptr;
const ::uint32_t
    TableStruct_webuimessages_5fachievements_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CAchievements_GetInfo_Request, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CAchievements_GetInfo_Request, _impl_.gameid_),
        0,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CAchievements_GetInfo_Response_Info, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CAchievements_GetInfo_Response_Info, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::CAchievements_GetInfo_Response_Info, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::CAchievements_GetInfo_Response_Info, _impl_.desc_),
        PROTOBUF_FIELD_OFFSET(::CAchievements_GetInfo_Response_Info, _impl_.image_url_achieved_),
        PROTOBUF_FIELD_OFFSET(::CAchievements_GetInfo_Response_Info, _impl_.image_url_not_achieved_),
        PROTOBUF_FIELD_OFFSET(::CAchievements_GetInfo_Response_Info, _impl_.achieved_),
        PROTOBUF_FIELD_OFFSET(::CAchievements_GetInfo_Response_Info, _impl_.unlock_time_),
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CAchievements_GetInfo_Response, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CAchievements_GetInfo_Response, _impl_.achievements_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::CAchievements_GetInfo_Request)},
        {5, sizeof(::CAchievements_GetInfo_Response_Info)},
        {22, sizeof(::CAchievements_GetInfo_Response)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_CAchievements_GetInfo_Request_default_instance_._instance,
    &::_CAchievements_GetInfo_Response_Info_default_instance_._instance,
    &::_CAchievements_GetInfo_Response_default_instance_._instance,
};
const char descriptor_table_protodef_webuimessages_5fachievements_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n webuimessages_achievements.proto\032\030stea"
    "mmessages_base.proto\032\030webuimessages_base"
    ".proto\"/\n\035CAchievements_GetInfo_Request\022"
    "\016\n\006gameid\030\001 \001(\004\"\360\001\n\036CAchievements_GetInf"
    "o_Response\022:\n\014achievements\030\001 \003(\0132$.CAchi"
    "evements_GetInfo_Response.Info\032\221\001\n\004Info\022"
    "\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\014\n\004desc\030\003 \001(\t\022"
    "\032\n\022image_url_achieved\030\004 \001(\t\022\036\n\026image_url"
    "_not_achieved\030\005 \001(\t\022\020\n\010achieved\030\006 \001(\010\022\023\n"
    "\013unlock_time\030\007 \001(\r2`\n\014Achievements\022J\n\007Ge"
    "tInfo\022\036.CAchievements_GetInfo_Request\032\037."
    "CAchievements_GetInfo_Response\032\004\200\227\"\002B\005H\001"
    "\220\001\001"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_webuimessages_5fachievements_2eproto_deps[2] = {
        &::descriptor_table_steammessages_5fbase_2eproto,
        &::descriptor_table_webuimessages_5fbase_2eproto,
};
static ::absl::once_flag descriptor_table_webuimessages_5fachievements_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_webuimessages_5fachievements_2eproto = {
    false,
    false,
    483,
    descriptor_table_protodef_webuimessages_5fachievements_2eproto,
    "webuimessages_achievements.proto",
    &descriptor_table_webuimessages_5fachievements_2eproto_once,
    descriptor_table_webuimessages_5fachievements_2eproto_deps,
    2,
    3,
    schemas,
    file_default_instances,
    TableStruct_webuimessages_5fachievements_2eproto::offsets,
    file_level_enum_descriptors_webuimessages_5fachievements_2eproto,
    file_level_service_descriptors_webuimessages_5fachievements_2eproto,
};
// ===================================================================

class CAchievements_GetInfo_Request::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CAchievements_GetInfo_Request>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Request, _impl_._has_bits_);
};

CAchievements_GetInfo_Request::CAchievements_GetInfo_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CAchievements_GetInfo_Request_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CAchievements_GetInfo_Request)
}
CAchievements_GetInfo_Request::CAchievements_GetInfo_Request(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const CAchievements_GetInfo_Request& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CAchievements_GetInfo_Request_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CAchievements_GetInfo_Request::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0} {}

inline void CAchievements_GetInfo_Request::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.gameid_ = {};
}
CAchievements_GetInfo_Request::~CAchievements_GetInfo_Request() {
  // @@protoc_insertion_point(destructor:CAchievements_GetInfo_Request)
  SharedDtor(*this);
}
inline void CAchievements_GetInfo_Request::SharedDtor(MessageLite& self) {
  CAchievements_GetInfo_Request& this_ = static_cast<CAchievements_GetInfo_Request&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CAchievements_GetInfo_Request::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CAchievements_GetInfo_Request(arena);
}
constexpr auto CAchievements_GetInfo_Request::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CAchievements_GetInfo_Request),
                                            alignof(CAchievements_GetInfo_Request));
}
constexpr auto CAchievements_GetInfo_Request::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CAchievements_GetInfo_Request_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CAchievements_GetInfo_Request::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CAchievements_GetInfo_Request>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CAchievements_GetInfo_Request::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CAchievements_GetInfo_Request>(), &CAchievements_GetInfo_Request::ByteSizeLong,
              &CAchievements_GetInfo_Request::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Request, _impl_._cached_size_),
          false,
      },
      &CAchievements_GetInfo_Request::kDescriptorMethods,
      &descriptor_table_webuimessages_5fachievements_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CAchievements_GetInfo_Request_class_data_ =
        CAchievements_GetInfo_Request::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CAchievements_GetInfo_Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CAchievements_GetInfo_Request_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CAchievements_GetInfo_Request_class_data_.tc_table);
  return CAchievements_GetInfo_Request_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
CAchievements_GetInfo_Request::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Request, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CAchievements_GetInfo_Request_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CAchievements_GetInfo_Request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // optional uint64 gameid = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CAchievements_GetInfo_Request, _impl_.gameid_), 0>(),
     {8, 0, 0,
      PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Request, _impl_.gameid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional uint64 gameid = 1;
    {PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Request, _impl_.gameid_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CAchievements_GetInfo_Request::Clear() {
// @@protoc_insertion_point(message_clear_start:CAchievements_GetInfo_Request)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.gameid_ = ::uint64_t{0u};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CAchievements_GetInfo_Request::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CAchievements_GetInfo_Request& this_ = static_cast<const CAchievements_GetInfo_Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CAchievements_GetInfo_Request::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CAchievements_GetInfo_Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CAchievements_GetInfo_Request)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional uint64 gameid = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        1, this_._internal_gameid(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CAchievements_GetInfo_Request)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CAchievements_GetInfo_Request::ByteSizeLong(const MessageLite& base) {
  const CAchievements_GetInfo_Request& this_ = static_cast<const CAchievements_GetInfo_Request&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CAchievements_GetInfo_Request::ByteSizeLong() const {
  const CAchievements_GetInfo_Request& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CAchievements_GetInfo_Request)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

   {
    // optional uint64 gameid = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_gameid());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CAchievements_GetInfo_Request::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CAchievements_GetInfo_Request*>(&to_msg);
  auto& from = static_cast<const CAchievements_GetInfo_Request&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CAchievements_GetInfo_Request)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _this->_impl_.gameid_ = from._impl_.gameid_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CAchievements_GetInfo_Request::CopyFrom(const CAchievements_GetInfo_Request& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CAchievements_GetInfo_Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CAchievements_GetInfo_Request::InternalSwap(CAchievements_GetInfo_Request* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.gameid_, other->_impl_.gameid_);
}

::google::protobuf::Metadata CAchievements_GetInfo_Request::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CAchievements_GetInfo_Response_Info::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CAchievements_GetInfo_Response_Info>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_._has_bits_);
};

CAchievements_GetInfo_Response_Info::CAchievements_GetInfo_Response_Info(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CAchievements_GetInfo_Response_Info_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CAchievements_GetInfo_Response.Info)
}
PROTOBUF_NDEBUG_INLINE CAchievements_GetInfo_Response_Info::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CAchievements_GetInfo_Response_Info& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        id_(arena, from.id_),
        name_(arena, from.name_),
        desc_(arena, from.desc_),
        image_url_achieved_(arena, from.image_url_achieved_),
        image_url_not_achieved_(arena, from.image_url_not_achieved_) {}

CAchievements_GetInfo_Response_Info::CAchievements_GetInfo_Response_Info(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CAchievements_GetInfo_Response_Info& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CAchievements_GetInfo_Response_Info_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CAchievements_GetInfo_Response_Info* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, achieved_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, achieved_),
           offsetof(Impl_, unlock_time_) -
               offsetof(Impl_, achieved_) +
               sizeof(Impl_::unlock_time_));

  // @@protoc_insertion_point(copy_constructor:CAchievements_GetInfo_Response.Info)
}
PROTOBUF_NDEBUG_INLINE CAchievements_GetInfo_Response_Info::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        id_(arena),
        name_(arena),
        desc_(arena),
        image_url_achieved_(arena),
        image_url_not_achieved_(arena) {}

inline void CAchievements_GetInfo_Response_Info::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, achieved_),
           0,
           offsetof(Impl_, unlock_time_) -
               offsetof(Impl_, achieved_) +
               sizeof(Impl_::unlock_time_));
}
CAchievements_GetInfo_Response_Info::~CAchievements_GetInfo_Response_Info() {
  // @@protoc_insertion_point(destructor:CAchievements_GetInfo_Response.Info)
  SharedDtor(*this);
}
inline void CAchievements_GetInfo_Response_Info::SharedDtor(MessageLite& self) {
  CAchievements_GetInfo_Response_Info& this_ = static_cast<CAchievements_GetInfo_Response_Info&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.name_.Destroy();
  this_._impl_.desc_.Destroy();
  this_._impl_.image_url_achieved_.Destroy();
  this_._impl_.image_url_not_achieved_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CAchievements_GetInfo_Response_Info::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CAchievements_GetInfo_Response_Info(arena);
}
constexpr auto CAchievements_GetInfo_Response_Info::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CAchievements_GetInfo_Response_Info),
                                            alignof(CAchievements_GetInfo_Response_Info));
}
constexpr auto CAchievements_GetInfo_Response_Info::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CAchievements_GetInfo_Response_Info_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CAchievements_GetInfo_Response_Info::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CAchievements_GetInfo_Response_Info>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CAchievements_GetInfo_Response_Info::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CAchievements_GetInfo_Response_Info>(), &CAchievements_GetInfo_Response_Info::ByteSizeLong,
              &CAchievements_GetInfo_Response_Info::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_._cached_size_),
          false,
      },
      &CAchievements_GetInfo_Response_Info::kDescriptorMethods,
      &descriptor_table_webuimessages_5fachievements_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CAchievements_GetInfo_Response_Info_class_data_ =
        CAchievements_GetInfo_Response_Info::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CAchievements_GetInfo_Response_Info::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CAchievements_GetInfo_Response_Info_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CAchievements_GetInfo_Response_Info_class_data_.tc_table);
  return CAchievements_GetInfo_Response_Info_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 7, 0, 0, 2>
CAchievements_GetInfo_Response_Info::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_._has_bits_),
    0, // no _extensions_
    7, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967168,  // skipmap
    offsetof(decltype(_table_), field_entries),
    7,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CAchievements_GetInfo_Response_Info_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CAchievements_GetInfo_Response_Info>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional string id = 1;
    {::_pbi::TcParser::FastBS1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.id_)}},
    // optional string name = 2;
    {::_pbi::TcParser::FastBS1,
     {18, 1, 0,
      PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.name_)}},
    // optional string desc = 3;
    {::_pbi::TcParser::FastBS1,
     {26, 2, 0,
      PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.desc_)}},
    // optional string image_url_achieved = 4;
    {::_pbi::TcParser::FastBS1,
     {34, 3, 0,
      PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.image_url_achieved_)}},
    // optional string image_url_not_achieved = 5;
    {::_pbi::TcParser::FastBS1,
     {42, 4, 0,
      PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.image_url_not_achieved_)}},
    // optional bool achieved = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CAchievements_GetInfo_Response_Info, _impl_.achieved_), 5>(),
     {48, 5, 0,
      PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.achieved_)}},
    // optional uint32 unlock_time = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CAchievements_GetInfo_Response_Info, _impl_.unlock_time_), 6>(),
     {56, 6, 0,
      PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.unlock_time_)}},
  }}, {{
    65535, 65535
  }}, {{
    // optional string id = 1;
    {PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.id_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional string name = 2;
    {PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.name_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional string desc = 3;
    {PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.desc_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional string image_url_achieved = 4;
    {PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.image_url_achieved_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional string image_url_not_achieved = 5;
    {PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.image_url_not_achieved_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional bool achieved = 6;
    {PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.achieved_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
    // optional uint32 unlock_time = 7;
    {PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.unlock_time_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt32)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CAchievements_GetInfo_Response_Info::Clear() {
// @@protoc_insertion_point(message_clear_start:CAchievements_GetInfo_Response.Info)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.id_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.name_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.desc_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _impl_.image_url_achieved_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.image_url_not_achieved_.ClearNonDefaultToEmpty();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000060U)) {
    ::memset(&_impl_.achieved_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.unlock_time_) -
        reinterpret_cast<char*>(&_impl_.achieved_)) + sizeof(_impl_.unlock_time_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CAchievements_GetInfo_Response_Info::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CAchievements_GetInfo_Response_Info& this_ = static_cast<const CAchievements_GetInfo_Response_Info&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CAchievements_GetInfo_Response_Info::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CAchievements_GetInfo_Response_Info& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CAchievements_GetInfo_Response.Info)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_id();
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // optional string name = 2;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    const ::std::string& _s = this_._internal_name();
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional string desc = 3;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    const ::std::string& _s = this_._internal_desc();
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string image_url_achieved = 4;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    const ::std::string& _s = this_._internal_image_url_achieved();
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // optional string image_url_not_achieved = 5;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    const ::std::string& _s = this_._internal_image_url_not_achieved();
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  // optional bool achieved = 6;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        6, this_._internal_achieved(), target);
  }

  // optional uint32 unlock_time = 7;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        7, this_._internal_unlock_time(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CAchievements_GetInfo_Response.Info)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CAchievements_GetInfo_Response_Info::ByteSizeLong(const MessageLite& base) {
  const CAchievements_GetInfo_Response_Info& this_ = static_cast<const CAchievements_GetInfo_Response_Info&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CAchievements_GetInfo_Response_Info::ByteSizeLong() const {
  const CAchievements_GetInfo_Response_Info& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CAchievements_GetInfo_Response.Info)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000020U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x0000005fU)) {
    // optional string id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_id());
    }
    // optional string name = 2;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_name());
    }
    // optional string desc = 3;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_desc());
    }
    // optional string image_url_achieved = 4;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_image_url_achieved());
    }
    // optional string image_url_not_achieved = 5;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_image_url_not_achieved());
    }
    // optional uint32 unlock_time = 7;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
          this_._internal_unlock_time());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CAchievements_GetInfo_Response_Info::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CAchievements_GetInfo_Response_Info*>(&to_msg);
  auto& from = static_cast<const CAchievements_GetInfo_Response_Info&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CAchievements_GetInfo_Response.Info)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_id(from._internal_id());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_set_name(from._internal_name());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_set_desc(from._internal_desc());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_internal_set_image_url_achieved(from._internal_image_url_achieved());
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_internal_set_image_url_not_achieved(from._internal_image_url_not_achieved());
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.achieved_ = from._impl_.achieved_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.unlock_time_ = from._impl_.unlock_time_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CAchievements_GetInfo_Response_Info::CopyFrom(const CAchievements_GetInfo_Response_Info& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CAchievements_GetInfo_Response.Info)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CAchievements_GetInfo_Response_Info::InternalSwap(CAchievements_GetInfo_Response_Info* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.desc_, &other->_impl_.desc_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_url_achieved_, &other->_impl_.image_url_achieved_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.image_url_not_achieved_, &other->_impl_.image_url_not_achieved_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.unlock_time_)
      + sizeof(CAchievements_GetInfo_Response_Info::_impl_.unlock_time_)
      - PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response_Info, _impl_.achieved_)>(
          reinterpret_cast<char*>(&_impl_.achieved_),
          reinterpret_cast<char*>(&other->_impl_.achieved_));
}

::google::protobuf::Metadata CAchievements_GetInfo_Response_Info::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CAchievements_GetInfo_Response::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CAchievements_GetInfo_Response>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response, _impl_._has_bits_);
};

CAchievements_GetInfo_Response::CAchievements_GetInfo_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CAchievements_GetInfo_Response_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CAchievements_GetInfo_Response)
}
PROTOBUF_NDEBUG_INLINE CAchievements_GetInfo_Response::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CAchievements_GetInfo_Response& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        achievements_{visibility, arena, from.achievements_} {}

CAchievements_GetInfo_Response::CAchievements_GetInfo_Response(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CAchievements_GetInfo_Response& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CAchievements_GetInfo_Response_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CAchievements_GetInfo_Response* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:CAchievements_GetInfo_Response)
}
PROTOBUF_NDEBUG_INLINE CAchievements_GetInfo_Response::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        achievements_{visibility, arena} {}

inline void CAchievements_GetInfo_Response::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CAchievements_GetInfo_Response::~CAchievements_GetInfo_Response() {
  // @@protoc_insertion_point(destructor:CAchievements_GetInfo_Response)
  SharedDtor(*this);
}
inline void CAchievements_GetInfo_Response::SharedDtor(MessageLite& self) {
  CAchievements_GetInfo_Response& this_ = static_cast<CAchievements_GetInfo_Response&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CAchievements_GetInfo_Response::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CAchievements_GetInfo_Response(arena);
}
constexpr auto CAchievements_GetInfo_Response::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response, _impl_.achievements_) +
          decltype(CAchievements_GetInfo_Response::_impl_.achievements_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(CAchievements_GetInfo_Response), alignof(CAchievements_GetInfo_Response), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CAchievements_GetInfo_Response::PlacementNew_,
                                 sizeof(CAchievements_GetInfo_Response),
                                 alignof(CAchievements_GetInfo_Response));
  }
}
constexpr auto CAchievements_GetInfo_Response::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CAchievements_GetInfo_Response_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CAchievements_GetInfo_Response::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CAchievements_GetInfo_Response>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CAchievements_GetInfo_Response::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CAchievements_GetInfo_Response>(), &CAchievements_GetInfo_Response::ByteSizeLong,
              &CAchievements_GetInfo_Response::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response, _impl_._cached_size_),
          false,
      },
      &CAchievements_GetInfo_Response::kDescriptorMethods,
      &descriptor_table_webuimessages_5fachievements_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CAchievements_GetInfo_Response_class_data_ =
        CAchievements_GetInfo_Response::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CAchievements_GetInfo_Response::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CAchievements_GetInfo_Response_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CAchievements_GetInfo_Response_class_data_.tc_table);
  return CAchievements_GetInfo_Response_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
CAchievements_GetInfo_Response::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CAchievements_GetInfo_Response_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CAchievements_GetInfo_Response>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .CAchievements_GetInfo_Response.Info achievements = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response, _impl_.achievements_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .CAchievements_GetInfo_Response.Info achievements = 1;
    {PROTOBUF_FIELD_OFFSET(CAchievements_GetInfo_Response, _impl_.achievements_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::CAchievements_GetInfo_Response_Info>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void CAchievements_GetInfo_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:CAchievements_GetInfo_Response)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.achievements_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CAchievements_GetInfo_Response::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CAchievements_GetInfo_Response& this_ = static_cast<const CAchievements_GetInfo_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CAchievements_GetInfo_Response::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CAchievements_GetInfo_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CAchievements_GetInfo_Response)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .CAchievements_GetInfo_Response.Info achievements = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_achievements_size());
         i < n; i++) {
      const auto& repfield = this_._internal_achievements().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CAchievements_GetInfo_Response)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CAchievements_GetInfo_Response::ByteSizeLong(const MessageLite& base) {
  const CAchievements_GetInfo_Response& this_ = static_cast<const CAchievements_GetInfo_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CAchievements_GetInfo_Response::ByteSizeLong() const {
  const CAchievements_GetInfo_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CAchievements_GetInfo_Response)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .CAchievements_GetInfo_Response.Info achievements = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_achievements_size();
      for (const auto& msg : this_._internal_achievements()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CAchievements_GetInfo_Response::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CAchievements_GetInfo_Response*>(&to_msg);
  auto& from = static_cast<const CAchievements_GetInfo_Response&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:CAchievements_GetInfo_Response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_achievements()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_achievements());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CAchievements_GetInfo_Response::CopyFrom(const CAchievements_GetInfo_Response& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CAchievements_GetInfo_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CAchievements_GetInfo_Response::InternalSwap(CAchievements_GetInfo_Response* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.achievements_.InternalSwap(&other->_impl_.achievements_);
}

::google::protobuf::Metadata CAchievements_GetInfo_Response::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_webuimessages_5fachievements_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
