// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: webuimessages_base.proto
// Protobuf C++ Version: 6.33.5

#include "webuimessages_base.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
template <typename>
PROTOBUF_CONSTEXPR WebUINoResponse::WebUINoResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(WebUINoResponse_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct WebUINoResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR WebUINoResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~WebUINoResponseDefaultTypeInternal() {}
  union {
    WebUINoResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 WebUINoResponseDefaultTypeInternal _WebUINoResponse_default_instance_;
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL
    file_level_enum_descriptors_webuimessages_5fbase_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_webuimessages_5fbase_2eproto = nullptr;
const ::uint32_t
    TableStruct_webuimessages_5fbase_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::WebUINoResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_WebUINoResponse_default_instance_._instance,
};
const char descriptor_table_protodef_webuimessages_5fbase_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\030webuimessages_base.proto\032\013enums.proto\032"
    "\030steammessages_base.proto\032 google/protob"
    "uf/descriptor.proto\"\021\n\017WebUINoResponse*\240"
    "\001\n\024EClientExecutionSite\022!\n\035k_EClientExec"
    "utionSiteInvalid\020\000\022!\n\035k_EClientExecution"
    "SiteSteamUI\020\001\022#\n\037k_EClientExecutionSiteC"
    "lientdll\020\002\022\035\n\031k_EClientExecutionSiteAny\020"
    "\003:}\n\034webui_service_execution_site\022\037.goog"
    "le.protobuf.ServiceOptions\030\360\242\004 \001(\0162\025.ECl"
    "ientExecutionSite:\035k_EClientExecutionSit"
    "eSteamUI:{\n\033webui_method_execution_site\022"
    "\036.google.protobuf.MethodOptions\030\360\242\004 \001(\0162"
    "\025.EClientExecutionSite:\035k_EClientExecuti"
    "onSiteInvalidB\005H\001\220\001\001"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_webuimessages_5fbase_2eproto_deps[3] = {
        &::descriptor_table_enums_2eproto,
        &::descriptor_table_google_2fprotobuf_2fdescriptor_2eproto,
        &::descriptor_table_steammessages_5fbase_2eproto,
};
static ::absl::once_flag descriptor_table_webuimessages_5fbase_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_webuimessages_5fbase_2eproto = {
    false,
    false,
    540,
    descriptor_table_protodef_webuimessages_5fbase_2eproto,
    "webuimessages_base.proto",
    &descriptor_table_webuimessages_5fbase_2eproto_once,
    descriptor_table_webuimessages_5fbase_2eproto_deps,
    3,
    1,
    schemas,
    file_default_instances,
    TableStruct_webuimessages_5fbase_2eproto::offsets,
    file_level_enum_descriptors_webuimessages_5fbase_2eproto,
    file_level_service_descriptors_webuimessages_5fbase_2eproto,
};
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL EClientExecutionSite_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_webuimessages_5fbase_2eproto);
  return file_level_enum_descriptors_webuimessages_5fbase_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t EClientExecutionSite_internal_data_[] = {
    262144u, 0u, };
// ===================================================================

class WebUINoResponse::_Internal {
 public:
};

WebUINoResponse::WebUINoResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, WebUINoResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:WebUINoResponse)
}
WebUINoResponse::WebUINoResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const WebUINoResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, WebUINoResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  WebUINoResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:WebUINoResponse)
}

inline void* PROTOBUF_NONNULL WebUINoResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) WebUINoResponse(arena);
}
constexpr auto WebUINoResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(WebUINoResponse),
                                            alignof(WebUINoResponse));
}
constexpr auto WebUINoResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_WebUINoResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &WebUINoResponse::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<WebUINoResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &WebUINoResponse::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<WebUINoResponse>(), &WebUINoResponse::ByteSizeLong,
              &WebUINoResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(WebUINoResponse, _impl_._cached_size_),
          false,
      },
      &WebUINoResponse::kDescriptorMethods,
      &descriptor_table_webuimessages_5fbase_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull WebUINoResponse_class_data_ =
        WebUINoResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
WebUINoResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&WebUINoResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(WebUINoResponse_class_data_.tc_table);
  return WebUINoResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
WebUINoResponse::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    WebUINoResponse_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::WebUINoResponse>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata WebUINoResponse::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::ServiceOptions, ::_pbi::EnumTypeTraits< ::EClientExecutionSite>, 14, false>
        webui_service_execution_site(kWebuiServiceExecutionSiteFieldNumber, static_cast< ::EClientExecutionSite >(1));
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 ::_pbi::ExtensionIdentifier<
        ::google::protobuf::MethodOptions, ::_pbi::EnumTypeTraits< ::EClientExecutionSite>, 14, false>
        webui_method_execution_site(kWebuiMethodExecutionSiteFieldNumber, static_cast< ::EClientExecutionSite >(0));
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_webuimessages_5fbase_2eproto),
        ::_pbi::ExtensionSet::RegisterEnumExtension(
            &::google::protobuf::ServiceOptions::default_instance(), 70000, 14,
            false, false, ::EClientExecutionSite_internal_data_),
        ::_pbi::ExtensionSet::RegisterEnumExtension(
            &::google::protobuf::MethodOptions::default_instance(), 70000, 14,
            false, false, ::EClientExecutionSite_internal_data_),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
