// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: webuimessages_base.proto
// Protobuf C++ Version: 6.33.5

#ifndef webuimessages_5fbase_2eproto_2epb_2eh
#define webuimessages_5fbase_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_bases.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "enums.pb.h"
#include "steammessages_base.pb.h"
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_webuimessages_5fbase_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_webuimessages_5fbase_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_webuimessages_5fbase_2eproto;
}  // extern "C"
enum EClientExecutionSite : int;
extern const uint32_t EClientExecutionSite_internal_data_[];
class WebUINoResponse;
struct WebUINoResponseDefaultTypeInternal;
extern WebUINoResponseDefaultTypeInternal _WebUINoResponse_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull WebUINoResponse_class_data_;
namespace google {
namespace protobuf {
template <>
internal::EnumTraitsT<::EClientExecutionSite_internal_data_>
    internal::EnumTraitsImpl::value<::EClientExecutionSite>;
}  // namespace protobuf
}  // namespace google

enum EClientExecutionSite : int {
  k_EClientExecutionSiteInvalid = 0,
  k_EClientExecutionSiteSteamUI = 1,
  k_EClientExecutionSiteClientdll = 2,
  k_EClientExecutionSiteAny = 3,
};

extern const uint32_t EClientExecutionSite_internal_data_[];
inline constexpr EClientExecutionSite EClientExecutionSite_MIN =
    static_cast<EClientExecutionSite>(0);
inline constexpr EClientExecutionSite EClientExecutionSite_MAX =
    static_cast<EClientExecutionSite>(3);
inline bool EClientExecutionSite_IsValid(int value) {
  return 0 <= value && value <= 3;
}
inline constexpr int EClientExecutionSite_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL EClientExecutionSite_descriptor();
template <typename T>
const ::std::string& EClientExecutionSite_Name(T value) {
  static_assert(::std::is_same<T, EClientExecutionSite>::value ||
                    ::std::is_integral<T>::value,
                "Incorrect type passed to EClientExecutionSite_Name().");
  return EClientExecutionSite_Name(static_cast<EClientExecutionSite>(value));
}
template <>
inline const ::std::string& EClientExecutionSite_Name(EClientExecutionSite value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EClientExecutionSite_descriptor, 0, 3>(
      static_cast<int>(value));
}
inline bool EClientExecutionSite_Parse(
    ::absl::string_view name, EClientExecutionSite* PROTOBUF_NONNULL value) {
  return ::google::protobuf::internal::ParseNamedEnum<EClientExecutionSite>(EClientExecutionSite_descriptor(), name,
                                           value);
}

// ===================================================================


// -------------------------------------------------------------------

class WebUINoResponse final : public ::google::protobuf::internal::ZeroFieldsBase
/* @@protoc_insertion_point(class_definition:WebUINoResponse) */ {
 public:
  inline WebUINoResponse() : WebUINoResponse(nullptr) {}

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(WebUINoResponse* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(WebUINoResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR WebUINoResponse(::google::protobuf::internal::ConstantInitialized);

  inline WebUINoResponse(const WebUINoResponse& from) : WebUINoResponse(nullptr, from) {}
  inline WebUINoResponse(WebUINoResponse&& from) noexcept
      : WebUINoResponse(nullptr, ::std::move(from)) {}
  inline WebUINoResponse& operator=(const WebUINoResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline WebUINoResponse& operator=(WebUINoResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const WebUINoResponse& default_instance() {
    return *reinterpret_cast<const WebUINoResponse*>(
        &_WebUINoResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(WebUINoResponse& a, WebUINoResponse& b) { a.Swap(&b); }
  inline void Swap(WebUINoResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(WebUINoResponse* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  WebUINoResponse* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::internal::ZeroFieldsBase::DefaultConstruct<WebUINoResponse>(arena);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::CopyFrom;
  inline void CopyFrom(const WebUINoResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::CopyImpl(*this, from);
  }
  using ::google::protobuf::internal::ZeroFieldsBase::MergeFrom;
  void MergeFrom(const WebUINoResponse& from) {
    ::google::protobuf::internal::ZeroFieldsBase::MergeImpl(*this, from);
  }

  public:
  bool IsInitialized() const {
    return true;
  }
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "WebUINoResponse"; }

  explicit WebUINoResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  WebUINoResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const WebUINoResponse& from);
  WebUINoResponse(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, WebUINoResponse&& from) noexcept
      : WebUINoResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  // @@protoc_insertion_point(class_scope:WebUINoResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<0, 0,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  friend struct ::TableStruct_webuimessages_5fbase_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull WebUINoResponse_class_data_;

// ===================================================================



inline constexpr int kWebuiServiceExecutionSiteFieldNumber = 70000;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::ServiceOptions, ::google::protobuf::internal::EnumTypeTraits< ::EClientExecutionSite>, 14, false>
    webui_service_execution_site;
inline constexpr int kWebuiMethodExecutionSiteFieldNumber = 70000;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::MethodOptions, ::google::protobuf::internal::EnumTypeTraits< ::EClientExecutionSite>, 14, false>
    webui_method_execution_site;

// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// WebUINoResponse

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::EClientExecutionSite> : std::true_type {};
template <>
inline const EnumDescriptor* PROTOBUF_NONNULL GetEnumDescriptor<::EClientExecutionSite>() {
  return ::EClientExecutionSite_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // webuimessages_5fbase_2eproto_2epb_2eh
