// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: webuimessages_sharedjscontext.proto
// Protobuf C++ Version: 6.33.5

#include "webuimessages_sharedjscontext.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
template <typename>
PROTOBUF_CONSTEXPR CSharedJSContext_GetDesiredSteamUIWindows_Request::CSharedJSContext_GetDesiredSteamUIWindows_Request(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(CSharedJSContext_GetDesiredSteamUIWindows_Request_class_data_.base()){}
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase() {
}
#endif  // PROTOBUF_CUSTOM_VTABLE
struct CSharedJSContext_GetDesiredSteamUIWindows_RequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CSharedJSContext_GetDesiredSteamUIWindows_RequestDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CSharedJSContext_GetDesiredSteamUIWindows_RequestDefaultTypeInternal() {}
  union {
    CSharedJSContext_GetDesiredSteamUIWindows_Request _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CSharedJSContext_GetDesiredSteamUIWindows_RequestDefaultTypeInternal _CSharedJSContext_GetDesiredSteamUIWindows_Request_default_instance_;

inline constexpr CMsgSteamUIBrowserWindow::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        app_name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        id_{0},
        pid_{0},
        browser_id_{0},
        window_type_{0},
        x_{0},
        y_{0},
        appid_{::uint64_t{0u}},
        parent_window_handle_{::uint64_t{0u}},
        gamepadui_via_gamescope_{false} {}

template <typename>
PROTOBUF_CONSTEXPR CMsgSteamUIBrowserWindow::CMsgSteamUIBrowserWindow(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CMsgSteamUIBrowserWindow_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CMsgSteamUIBrowserWindowDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CMsgSteamUIBrowserWindowDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CMsgSteamUIBrowserWindowDefaultTypeInternal() {}
  union {
    CMsgSteamUIBrowserWindow _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CMsgSteamUIBrowserWindowDefaultTypeInternal _CMsgSteamUIBrowserWindow_default_instance_;

inline constexpr CSharedJSContext_GetDesiredSteamUIWindows_Response::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        windows_{} {}

template <typename>
PROTOBUF_CONSTEXPR CSharedJSContext_GetDesiredSteamUIWindows_Response::CSharedJSContext_GetDesiredSteamUIWindows_Response(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CSharedJSContext_GetDesiredSteamUIWindows_Response_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CSharedJSContext_GetDesiredSteamUIWindows_ResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CSharedJSContext_GetDesiredSteamUIWindows_ResponseDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~CSharedJSContext_GetDesiredSteamUIWindows_ResponseDefaultTypeInternal() {}
  union {
    CSharedJSContext_GetDesiredSteamUIWindows_Response _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CSharedJSContext_GetDesiredSteamUIWindows_ResponseDefaultTypeInternal _CSharedJSContext_GetDesiredSteamUIWindows_Response_default_instance_;
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_webuimessages_5fsharedjscontext_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_webuimessages_5fsharedjscontext_2eproto = nullptr;
const ::uint32_t
    TableStruct_webuimessages_5fsharedjscontext_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x000, // bitmap
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CMsgSteamUIBrowserWindow, _impl_._has_bits_),
        13, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CMsgSteamUIBrowserWindow, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::CMsgSteamUIBrowserWindow, _impl_.pid_),
        PROTOBUF_FIELD_OFFSET(::CMsgSteamUIBrowserWindow, _impl_.browser_id_),
        PROTOBUF_FIELD_OFFSET(::CMsgSteamUIBrowserWindow, _impl_.window_type_),
        PROTOBUF_FIELD_OFFSET(::CMsgSteamUIBrowserWindow, _impl_.x_),
        PROTOBUF_FIELD_OFFSET(::CMsgSteamUIBrowserWindow, _impl_.y_),
        PROTOBUF_FIELD_OFFSET(::CMsgSteamUIBrowserWindow, _impl_.appid_),
        PROTOBUF_FIELD_OFFSET(::CMsgSteamUIBrowserWindow, _impl_.parent_window_handle_),
        PROTOBUF_FIELD_OFFSET(::CMsgSteamUIBrowserWindow, _impl_.app_name_),
        PROTOBUF_FIELD_OFFSET(::CMsgSteamUIBrowserWindow, _impl_.gamepadui_via_gamescope_),
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        0,
        9,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::CSharedJSContext_GetDesiredSteamUIWindows_Response, _impl_._has_bits_),
        4, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::CSharedJSContext_GetDesiredSteamUIWindows_Response, _impl_.windows_),
        0,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::CSharedJSContext_GetDesiredSteamUIWindows_Request)},
        {1, sizeof(::CMsgSteamUIBrowserWindow)},
        {24, sizeof(::CSharedJSContext_GetDesiredSteamUIWindows_Response)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::_CSharedJSContext_GetDesiredSteamUIWindows_Request_default_instance_._instance,
    &::_CMsgSteamUIBrowserWindow_default_instance_._instance,
    &::_CSharedJSContext_GetDesiredSteamUIWindows_Response_default_instance_._instance,
};
const char descriptor_table_protodef_webuimessages_5fsharedjscontext_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n#webuimessages_sharedjscontext.proto\032\013e"
    "nums.proto\032\030steammessages_base.proto\032\030we"
    "buimessages_base.proto\"3\n1CSharedJSConte"
    "xt_GetDesiredSteamUIWindows_Request\"\322\001\n\030"
    "CMsgSteamUIBrowserWindow\022\n\n\002id\030\001 \001(\005\022\013\n\003"
    "pid\030\002 \001(\005\022\022\n\nbrowser_id\030\003 \001(\005\022\023\n\013window_"
    "type\030\004 \001(\005\022\t\n\001x\030\005 \001(\005\022\t\n\001y\030\006 \001(\005\022\r\n\005appi"
    "d\030\007 \001(\004\022\034\n\024parent_window_handle\030\010 \001(\004\022\020\n"
    "\010app_name\030\t \001(\t\022\037\n\027gamepadui_via_gamesco"
    "pe\030\n \001(\010\"`\n2CSharedJSContext_GetDesiredS"
    "teamUIWindows_Response\022*\n\007windows\030\001 \003(\0132"
    "\031.CMsgSteamUIBrowserWindow2\235\001\n\017SharedJSC"
    "ontext\022\203\001\n\030GetDesiredSteamUIWindows\0222.CS"
    "haredJSContext_GetDesiredSteamUIWindows_"
    "Request\0323.CSharedJSContext_GetDesiredSte"
    "amUIWindows_Response\032\004\200\227\"\001B\005H\001\220\001\001"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_webuimessages_5fsharedjscontext_2eproto_deps[3] = {
        &::descriptor_table_enums_2eproto,
        &::descriptor_table_steammessages_5fbase_2eproto,
        &::descriptor_table_webuimessages_5fbase_2eproto,
};
static ::absl::once_flag descriptor_table_webuimessages_5fsharedjscontext_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_webuimessages_5fsharedjscontext_2eproto = {
    false,
    false,
    633,
    descriptor_table_protodef_webuimessages_5fsharedjscontext_2eproto,
    "webuimessages_sharedjscontext.proto",
    &descriptor_table_webuimessages_5fsharedjscontext_2eproto_once,
    descriptor_table_webuimessages_5fsharedjscontext_2eproto_deps,
    3,
    3,
    schemas,
    file_default_instances,
    TableStruct_webuimessages_5fsharedjscontext_2eproto::offsets,
    file_level_enum_descriptors_webuimessages_5fsharedjscontext_2eproto,
    file_level_service_descriptors_webuimessages_5fsharedjscontext_2eproto,
};
// ===================================================================

class CSharedJSContext_GetDesiredSteamUIWindows_Request::_Internal {
 public:
};

CSharedJSContext_GetDesiredSteamUIWindows_Request::CSharedJSContext_GetDesiredSteamUIWindows_Request(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, CSharedJSContext_GetDesiredSteamUIWindows_Request_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(arena_constructor:CSharedJSContext_GetDesiredSteamUIWindows_Request)
}
CSharedJSContext_GetDesiredSteamUIWindows_Request::CSharedJSContext_GetDesiredSteamUIWindows_Request(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CSharedJSContext_GetDesiredSteamUIWindows_Request& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::internal::ZeroFieldsBase(arena, CSharedJSContext_GetDesiredSteamUIWindows_Request_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::internal::ZeroFieldsBase(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CSharedJSContext_GetDesiredSteamUIWindows_Request* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);

  // @@protoc_insertion_point(copy_constructor:CSharedJSContext_GetDesiredSteamUIWindows_Request)
}

inline void* PROTOBUF_NONNULL CSharedJSContext_GetDesiredSteamUIWindows_Request::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CSharedJSContext_GetDesiredSteamUIWindows_Request(arena);
}
constexpr auto CSharedJSContext_GetDesiredSteamUIWindows_Request::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(CSharedJSContext_GetDesiredSteamUIWindows_Request),
                                            alignof(CSharedJSContext_GetDesiredSteamUIWindows_Request));
}
constexpr auto CSharedJSContext_GetDesiredSteamUIWindows_Request::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CSharedJSContext_GetDesiredSteamUIWindows_Request_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CSharedJSContext_GetDesiredSteamUIWindows_Request::MergeImpl,
          ::google::protobuf::internal::ZeroFieldsBase::GetNewImpl<CSharedJSContext_GetDesiredSteamUIWindows_Request>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CSharedJSContext_GetDesiredSteamUIWindows_Request::SharedDtor,
          ::google::protobuf::internal::ZeroFieldsBase::GetClearImpl<CSharedJSContext_GetDesiredSteamUIWindows_Request>(), &CSharedJSContext_GetDesiredSteamUIWindows_Request::ByteSizeLong,
              &CSharedJSContext_GetDesiredSteamUIWindows_Request::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CSharedJSContext_GetDesiredSteamUIWindows_Request, _impl_._cached_size_),
          false,
      },
      &CSharedJSContext_GetDesiredSteamUIWindows_Request::kDescriptorMethods,
      &descriptor_table_webuimessages_5fsharedjscontext_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CSharedJSContext_GetDesiredSteamUIWindows_Request_class_data_ =
        CSharedJSContext_GetDesiredSteamUIWindows_Request::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CSharedJSContext_GetDesiredSteamUIWindows_Request::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CSharedJSContext_GetDesiredSteamUIWindows_Request_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CSharedJSContext_GetDesiredSteamUIWindows_Request_class_data_.tc_table);
  return CSharedJSContext_GetDesiredSteamUIWindows_Request_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 0, 0, 0, 2>
CSharedJSContext_GetDesiredSteamUIWindows_Request::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    0, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967295,  // skipmap
    offsetof(decltype(_table_), field_names),  // no field_entries
    0,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CSharedJSContext_GetDesiredSteamUIWindows_Request_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CSharedJSContext_GetDesiredSteamUIWindows_Request>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, // no field_entries, or aux_entries
  {{
  }},
};







::google::protobuf::Metadata CSharedJSContext_GetDesiredSteamUIWindows_Request::GetMetadata() const {
  return ::google::protobuf::internal::ZeroFieldsBase::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CMsgSteamUIBrowserWindow::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CMsgSteamUIBrowserWindow>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_._has_bits_);
};

CMsgSteamUIBrowserWindow::CMsgSteamUIBrowserWindow(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CMsgSteamUIBrowserWindow_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CMsgSteamUIBrowserWindow)
}
PROTOBUF_NDEBUG_INLINE CMsgSteamUIBrowserWindow::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CMsgSteamUIBrowserWindow& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        app_name_(arena, from.app_name_) {}

CMsgSteamUIBrowserWindow::CMsgSteamUIBrowserWindow(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CMsgSteamUIBrowserWindow& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CMsgSteamUIBrowserWindow_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CMsgSteamUIBrowserWindow* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           reinterpret_cast<const char*>(&from._impl_) +
               offsetof(Impl_, id_),
           offsetof(Impl_, gamepadui_via_gamescope_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::gamepadui_via_gamescope_));

  // @@protoc_insertion_point(copy_constructor:CMsgSteamUIBrowserWindow)
}
PROTOBUF_NDEBUG_INLINE CMsgSteamUIBrowserWindow::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        app_name_(arena) {}

inline void CMsgSteamUIBrowserWindow::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, id_),
           0,
           offsetof(Impl_, gamepadui_via_gamescope_) -
               offsetof(Impl_, id_) +
               sizeof(Impl_::gamepadui_via_gamescope_));
}
CMsgSteamUIBrowserWindow::~CMsgSteamUIBrowserWindow() {
  // @@protoc_insertion_point(destructor:CMsgSteamUIBrowserWindow)
  SharedDtor(*this);
}
inline void CMsgSteamUIBrowserWindow::SharedDtor(MessageLite& self) {
  CMsgSteamUIBrowserWindow& this_ = static_cast<CMsgSteamUIBrowserWindow&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.app_name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CMsgSteamUIBrowserWindow::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CMsgSteamUIBrowserWindow(arena);
}
constexpr auto CMsgSteamUIBrowserWindow::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(CMsgSteamUIBrowserWindow),
                                            alignof(CMsgSteamUIBrowserWindow));
}
constexpr auto CMsgSteamUIBrowserWindow::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CMsgSteamUIBrowserWindow_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CMsgSteamUIBrowserWindow::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CMsgSteamUIBrowserWindow>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CMsgSteamUIBrowserWindow::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CMsgSteamUIBrowserWindow>(), &CMsgSteamUIBrowserWindow::ByteSizeLong,
              &CMsgSteamUIBrowserWindow::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_._cached_size_),
          false,
      },
      &CMsgSteamUIBrowserWindow::kDescriptorMethods,
      &descriptor_table_webuimessages_5fsharedjscontext_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CMsgSteamUIBrowserWindow_class_data_ =
        CMsgSteamUIBrowserWindow::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CMsgSteamUIBrowserWindow::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CMsgSteamUIBrowserWindow_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CMsgSteamUIBrowserWindow_class_data_.tc_table);
  return CMsgSteamUIBrowserWindow_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<4, 10, 0, 0, 2>
CMsgSteamUIBrowserWindow::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_._has_bits_),
    0, // no _extensions_
    10, 120,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294966272,  // skipmap
    offsetof(decltype(_table_), field_entries),
    10,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    CMsgSteamUIBrowserWindow_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CMsgSteamUIBrowserWindow>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // optional int32 id = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CMsgSteamUIBrowserWindow, _impl_.id_), 1>(),
     {8, 1, 0,
      PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.id_)}},
    // optional int32 pid = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CMsgSteamUIBrowserWindow, _impl_.pid_), 2>(),
     {16, 2, 0,
      PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.pid_)}},
    // optional int32 browser_id = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CMsgSteamUIBrowserWindow, _impl_.browser_id_), 3>(),
     {24, 3, 0,
      PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.browser_id_)}},
    // optional int32 window_type = 4;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CMsgSteamUIBrowserWindow, _impl_.window_type_), 4>(),
     {32, 4, 0,
      PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.window_type_)}},
    // optional int32 x = 5;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CMsgSteamUIBrowserWindow, _impl_.x_), 5>(),
     {40, 5, 0,
      PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.x_)}},
    // optional int32 y = 6;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(CMsgSteamUIBrowserWindow, _impl_.y_), 6>(),
     {48, 6, 0,
      PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.y_)}},
    // optional uint64 appid = 7;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CMsgSteamUIBrowserWindow, _impl_.appid_), 7>(),
     {56, 7, 0,
      PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.appid_)}},
    // optional uint64 parent_window_handle = 8;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(CMsgSteamUIBrowserWindow, _impl_.parent_window_handle_), 8>(),
     {64, 8, 0,
      PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.parent_window_handle_)}},
    // optional string app_name = 9;
    {::_pbi::TcParser::FastBS1,
     {74, 0, 0,
      PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.app_name_)}},
    // optional bool gamepadui_via_gamescope = 10;
    {::_pbi::TcParser::SingularVarintNoZag1<bool, offsetof(CMsgSteamUIBrowserWindow, _impl_.gamepadui_via_gamescope_), 9>(),
     {80, 9, 0,
      PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.gamepadui_via_gamescope_)}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // optional int32 id = 1;
    {PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.id_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 pid = 2;
    {PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.pid_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 browser_id = 3;
    {PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.browser_id_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 window_type = 4;
    {PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.window_type_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 x = 5;
    {PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.x_), _Internal::kHasBitsOffset + 5, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional int32 y = 6;
    {PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.y_), _Internal::kHasBitsOffset + 6, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt32)},
    // optional uint64 appid = 7;
    {PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.appid_), _Internal::kHasBitsOffset + 7, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional uint64 parent_window_handle = 8;
    {PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.parent_window_handle_), _Internal::kHasBitsOffset + 8, 0, (0 | ::_fl::kFcOptional | ::_fl::kUInt64)},
    // optional string app_name = 9;
    {PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.app_name_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kBytes | ::_fl::kRepAString)},
    // optional bool gamepadui_via_gamescope = 10;
    {PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.gamepadui_via_gamescope_), _Internal::kHasBitsOffset + 9, 0, (0 | ::_fl::kFcOptional | ::_fl::kBool)},
  }},
  // no aux_entries
  {{
  }},
};
PROTOBUF_NOINLINE void CMsgSteamUIBrowserWindow::Clear() {
// @@protoc_insertion_point(message_clear_start:CMsgSteamUIBrowserWindow)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    _impl_.app_name_.ClearNonDefaultToEmpty();
  }
  if (BatchCheckHasBit(cached_has_bits, 0x000000feU)) {
    ::memset(&_impl_.id_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.appid_) -
        reinterpret_cast<char*>(&_impl_.id_)) + sizeof(_impl_.appid_));
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000300U)) {
    ::memset(&_impl_.parent_window_handle_, 0, static_cast<::size_t>(
        reinterpret_cast<char*>(&_impl_.gamepadui_via_gamescope_) -
        reinterpret_cast<char*>(&_impl_.parent_window_handle_)) + sizeof(_impl_.gamepadui_via_gamescope_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CMsgSteamUIBrowserWindow::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CMsgSteamUIBrowserWindow& this_ = static_cast<const CMsgSteamUIBrowserWindow&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CMsgSteamUIBrowserWindow::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CMsgSteamUIBrowserWindow& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CMsgSteamUIBrowserWindow)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int32 id = 1;
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<1>(
            stream, this_._internal_id(), target);
  }

  // optional int32 pid = 2;
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<2>(
            stream, this_._internal_pid(), target);
  }

  // optional int32 browser_id = 3;
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<3>(
            stream, this_._internal_browser_id(), target);
  }

  // optional int32 window_type = 4;
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<4>(
            stream, this_._internal_window_type(), target);
  }

  // optional int32 x = 5;
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<5>(
            stream, this_._internal_x(), target);
  }

  // optional int32 y = 6;
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    target =
        ::google::protobuf::internal::WireFormatLite::WriteInt32ToArrayWithField<6>(
            stream, this_._internal_y(), target);
  }

  // optional uint64 appid = 7;
  if (CheckHasBit(cached_has_bits, 0x00000080U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        7, this_._internal_appid(), target);
  }

  // optional uint64 parent_window_handle = 8;
  if (CheckHasBit(cached_has_bits, 0x00000100U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
        8, this_._internal_parent_window_handle(), target);
  }

  // optional string app_name = 9;
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    const ::std::string& _s = this_._internal_app_name();
    target = stream->WriteStringMaybeAliased(9, _s, target);
  }

  // optional bool gamepadui_via_gamescope = 10;
  if (CheckHasBit(cached_has_bits, 0x00000200U)) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        10, this_._internal_gamepadui_via_gamescope(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CMsgSteamUIBrowserWindow)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CMsgSteamUIBrowserWindow::ByteSizeLong(const MessageLite& base) {
  const CMsgSteamUIBrowserWindow& this_ = static_cast<const CMsgSteamUIBrowserWindow&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CMsgSteamUIBrowserWindow::ByteSizeLong() const {
  const CMsgSteamUIBrowserWindow& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CMsgSteamUIBrowserWindow)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000200U & cached_has_bits) * 2;
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    // optional string app_name = 9;
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                      this_._internal_app_name());
    }
    // optional int32 id = 1;
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_id());
    }
    // optional int32 pid = 2;
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_pid());
    }
    // optional int32 browser_id = 3;
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_browser_id());
    }
    // optional int32 window_type = 4;
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_window_type());
    }
    // optional int32 x = 5;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_x());
    }
    // optional int32 y = 6;
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(
          this_._internal_y());
    }
    // optional uint64 appid = 7;
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_appid());
    }
  }
   {
    // optional uint64 parent_window_handle = 8;
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
          this_._internal_parent_window_handle());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CMsgSteamUIBrowserWindow::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CMsgSteamUIBrowserWindow*>(&to_msg);
  auto& from = static_cast<const CMsgSteamUIBrowserWindow&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(class_specific_merge_from_start:CMsgSteamUIBrowserWindow)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x000000ffU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_set_app_name(from._internal_app_name());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_impl_.id_ = from._impl_.id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_impl_.pid_ = from._impl_.pid_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      _this->_impl_.browser_id_ = from._impl_.browser_id_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.window_type_ = from._impl_.window_type_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.x_ = from._impl_.x_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.y_ = from._impl_.y_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000080U)) {
      _this->_impl_.appid_ = from._impl_.appid_;
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000300U)) {
    if (CheckHasBit(cached_has_bits, 0x00000100U)) {
      _this->_impl_.parent_window_handle_ = from._impl_.parent_window_handle_;
    }
    if (CheckHasBit(cached_has_bits, 0x00000200U)) {
      _this->_impl_.gamepadui_via_gamescope_ = from._impl_.gamepadui_via_gamescope_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CMsgSteamUIBrowserWindow::CopyFrom(const CMsgSteamUIBrowserWindow& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CMsgSteamUIBrowserWindow)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CMsgSteamUIBrowserWindow::InternalSwap(CMsgSteamUIBrowserWindow* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.app_name_, &other->_impl_.app_name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.gamepadui_via_gamescope_)
      + sizeof(CMsgSteamUIBrowserWindow::_impl_.gamepadui_via_gamescope_)
      - PROTOBUF_FIELD_OFFSET(CMsgSteamUIBrowserWindow, _impl_.id_)>(
          reinterpret_cast<char*>(&_impl_.id_),
          reinterpret_cast<char*>(&other->_impl_.id_));
}

::google::protobuf::Metadata CMsgSteamUIBrowserWindow::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CSharedJSContext_GetDesiredSteamUIWindows_Response::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CSharedJSContext_GetDesiredSteamUIWindows_Response>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CSharedJSContext_GetDesiredSteamUIWindows_Response, _impl_._has_bits_);
};

CSharedJSContext_GetDesiredSteamUIWindows_Response::CSharedJSContext_GetDesiredSteamUIWindows_Response(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CSharedJSContext_GetDesiredSteamUIWindows_Response_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:CSharedJSContext_GetDesiredSteamUIWindows_Response)
}
PROTOBUF_NDEBUG_INLINE CSharedJSContext_GetDesiredSteamUIWindows_Response::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::CSharedJSContext_GetDesiredSteamUIWindows_Response& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        windows_{visibility, arena, from.windows_} {}

CSharedJSContext_GetDesiredSteamUIWindows_Response::CSharedJSContext_GetDesiredSteamUIWindows_Response(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CSharedJSContext_GetDesiredSteamUIWindows_Response& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CSharedJSContext_GetDesiredSteamUIWindows_Response_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  CSharedJSContext_GetDesiredSteamUIWindows_Response* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:CSharedJSContext_GetDesiredSteamUIWindows_Response)
}
PROTOBUF_NDEBUG_INLINE CSharedJSContext_GetDesiredSteamUIWindows_Response::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        windows_{visibility, arena} {}

inline void CSharedJSContext_GetDesiredSteamUIWindows_Response::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
CSharedJSContext_GetDesiredSteamUIWindows_Response::~CSharedJSContext_GetDesiredSteamUIWindows_Response() {
  // @@protoc_insertion_point(destructor:CSharedJSContext_GetDesiredSteamUIWindows_Response)
  SharedDtor(*this);
}
inline void CSharedJSContext_GetDesiredSteamUIWindows_Response::SharedDtor(MessageLite& self) {
  CSharedJSContext_GetDesiredSteamUIWindows_Response& this_ = static_cast<CSharedJSContext_GetDesiredSteamUIWindows_Response&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CSharedJSContext_GetDesiredSteamUIWindows_Response::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CSharedJSContext_GetDesiredSteamUIWindows_Response(arena);
}
constexpr auto CSharedJSContext_GetDesiredSteamUIWindows_Response::InternalNewImpl_() {
  constexpr auto arena_bits = ::google::protobuf::internal::EncodePlacementArenaOffsets({
      PROTOBUF_FIELD_OFFSET(CSharedJSContext_GetDesiredSteamUIWindows_Response, _impl_.windows_) +
          decltype(CSharedJSContext_GetDesiredSteamUIWindows_Response::_impl_.windows_)::
              InternalGetArenaOffset(
                  ::google::protobuf::Message::internal_visibility()),
  });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::ZeroInit(
        sizeof(CSharedJSContext_GetDesiredSteamUIWindows_Response), alignof(CSharedJSContext_GetDesiredSteamUIWindows_Response), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(&CSharedJSContext_GetDesiredSteamUIWindows_Response::PlacementNew_,
                                 sizeof(CSharedJSContext_GetDesiredSteamUIWindows_Response),
                                 alignof(CSharedJSContext_GetDesiredSteamUIWindows_Response));
  }
}
constexpr auto CSharedJSContext_GetDesiredSteamUIWindows_Response::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CSharedJSContext_GetDesiredSteamUIWindows_Response_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CSharedJSContext_GetDesiredSteamUIWindows_Response::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CSharedJSContext_GetDesiredSteamUIWindows_Response>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CSharedJSContext_GetDesiredSteamUIWindows_Response::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CSharedJSContext_GetDesiredSteamUIWindows_Response>(), &CSharedJSContext_GetDesiredSteamUIWindows_Response::ByteSizeLong,
              &CSharedJSContext_GetDesiredSteamUIWindows_Response::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CSharedJSContext_GetDesiredSteamUIWindows_Response, _impl_._cached_size_),
          false,
      },
      &CSharedJSContext_GetDesiredSteamUIWindows_Response::kDescriptorMethods,
      &descriptor_table_webuimessages_5fsharedjscontext_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull CSharedJSContext_GetDesiredSteamUIWindows_Response_class_data_ =
        CSharedJSContext_GetDesiredSteamUIWindows_Response::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
CSharedJSContext_GetDesiredSteamUIWindows_Response::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&CSharedJSContext_GetDesiredSteamUIWindows_Response_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(CSharedJSContext_GetDesiredSteamUIWindows_Response_class_data_.tc_table);
  return CSharedJSContext_GetDesiredSteamUIWindows_Response_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<0, 1, 1, 0, 2>
CSharedJSContext_GetDesiredSteamUIWindows_Response::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(CSharedJSContext_GetDesiredSteamUIWindows_Response, _impl_._has_bits_),
    0, // no _extensions_
    1, 0,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967294,  // skipmap
    offsetof(decltype(_table_), field_entries),
    1,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    CSharedJSContext_GetDesiredSteamUIWindows_Response_class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::CSharedJSContext_GetDesiredSteamUIWindows_Response>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    // repeated .CMsgSteamUIBrowserWindow windows = 1;
    {::_pbi::TcParser::FastMtR1,
     {10, 0, 0,
      PROTOBUF_FIELD_OFFSET(CSharedJSContext_GetDesiredSteamUIWindows_Response, _impl_.windows_)}},
  }}, {{
    65535, 65535
  }}, {{
    // repeated .CMsgSteamUIBrowserWindow windows = 1;
    {PROTOBUF_FIELD_OFFSET(CSharedJSContext_GetDesiredSteamUIWindows_Response, _impl_.windows_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
  }},
  {{
      {::_pbi::TcParser::GetTable<::CMsgSteamUIBrowserWindow>()},
  }},
  {{
  }},
};
PROTOBUF_NOINLINE void CSharedJSContext_GetDesiredSteamUIWindows_Response::Clear() {
// @@protoc_insertion_point(message_clear_start:CSharedJSContext_GetDesiredSteamUIWindows_Response)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _impl_.windows_.Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CSharedJSContext_GetDesiredSteamUIWindows_Response::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CSharedJSContext_GetDesiredSteamUIWindows_Response& this_ = static_cast<const CSharedJSContext_GetDesiredSteamUIWindows_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CSharedJSContext_GetDesiredSteamUIWindows_Response::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const CSharedJSContext_GetDesiredSteamUIWindows_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:CSharedJSContext_GetDesiredSteamUIWindows_Response)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // repeated .CMsgSteamUIBrowserWindow windows = 1;
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_windows_size());
         i < n; i++) {
      const auto& repfield = this_._internal_windows().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              1, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:CSharedJSContext_GetDesiredSteamUIWindows_Response)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CSharedJSContext_GetDesiredSteamUIWindows_Response::ByteSizeLong(const MessageLite& base) {
  const CSharedJSContext_GetDesiredSteamUIWindows_Response& this_ = static_cast<const CSharedJSContext_GetDesiredSteamUIWindows_Response&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CSharedJSContext_GetDesiredSteamUIWindows_Response::ByteSizeLong() const {
  const CSharedJSContext_GetDesiredSteamUIWindows_Response& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:CSharedJSContext_GetDesiredSteamUIWindows_Response)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
   {
    // repeated .CMsgSteamUIBrowserWindow windows = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_windows_size();
      for (const auto& msg : this_._internal_windows()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CSharedJSContext_GetDesiredSteamUIWindows_Response::MergeImpl(::google::protobuf::MessageLite& to_msg,
                            const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this =
      static_cast<CSharedJSContext_GetDesiredSteamUIWindows_Response*>(&to_msg);
  auto& from = static_cast<const CSharedJSContext_GetDesiredSteamUIWindows_Response&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:CSharedJSContext_GetDesiredSteamUIWindows_Response)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (CheckHasBitForRepeated(cached_has_bits, 0x00000001U)) {
    _this->_internal_mutable_windows()->InternalMergeFromWithArena(
        ::google::protobuf::MessageLite::internal_visibility(), arena,
        from._internal_windows());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CSharedJSContext_GetDesiredSteamUIWindows_Response::CopyFrom(const CSharedJSContext_GetDesiredSteamUIWindows_Response& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:CSharedJSContext_GetDesiredSteamUIWindows_Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void CSharedJSContext_GetDesiredSteamUIWindows_Response::InternalSwap(CSharedJSContext_GetDesiredSteamUIWindows_Response* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.windows_.InternalSwap(&other->_impl_.windows_);
}

::google::protobuf::Metadata CSharedJSContext_GetDesiredSteamUIWindows_Response::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_webuimessages_5fsharedjscontext_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
