set(PROTO_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/resources/protobufs)
set(PROTO_OUTPUT_DIR ${CMAKE_CURRENT_BINARY_DIR}/generated)

file(GLOB_RECURSE PROTO_FILES CONFIGURE_DEPENDS
    ${PROTO_ROOT}/*.proto
)

file(MAKE_DIRECTORY ${PROTO_OUTPUT_DIR})

find_package(Protobuf REQUIRED)

protobuf_generate(
    LANGUAGE cpp
    PROTOS ${PROTO_FILES}
    IMPORT_DIRS ${PROTO_ROOT}
    APPEND_PATH FALSE
    PROTOC_OUT_DIR ${PROTO_OUTPUT_DIR}
    OUT_VAR GENERATED_PROTO_SRCS
)